import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "npm:@supabase/server";
import { createHash } from "node:crypto";
const ORIGIN="https://drmacze.github.io";
const cors=()=>({"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"});
async function readBody(req:Request){const t=(req.headers.get("content-type")||"").toLowerCase();if(t.includes("application/x-www-form-urlencoded"))return Object.fromEntries(new URLSearchParams(await req.text()).entries());return await req.json().catch(()=>({}))}
function safe(v:unknown,n=600){return String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,n)}
function md5(v:string){return createHash("md5").update(v).digest("hex")}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function refId(){return `DLVIAK-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().replaceAll("-","").slice(0,8).toUpperCase()}`}
function jakartaKey(v:Date|string=new Date()){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(v))}
function jakartaEndOfDay(){return new Date(`${jakartaKey()}T23:59:59+07:00`).toISOString()}
async function vault(db:any,name:string){const q=await db.rpc("dlavie_get_vault_secret",{p_name:name});if(q.error)throw q.error;return String(q.data||"")}
async function settings(db:any){const q=await db.from("dlavie_iak_settings").select("*").eq("id",1).single();if(q.error)throw q.error;return q.data}
async function authWallet(db:any,token:string){if(!token)return null;const q=await db.from("dlavie_wallets").select("id,balance").eq("access_hash",await sha256(token)).maybeSingle();if(q.error)throw q.error;return q.data}
async function walletBalance(db:any,walletId:string){const q=await db.from("dlavie_wallets").select("balance").eq("id",walletId).maybeSingle();if(q.error)throw q.error;return Number(q.data?.balance||0)}
function sell(base:number,s:any){const min=Math.max(0,Number(s.minimum_markup||0)),v=Number(s.markup_value||0),m=s.markup_mode==="percent"?Math.max(min,Math.round(base*v/100)):Math.max(min,Math.round(v));return Math.max(base,base+m)}
async function post(url:string,payload:any){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`iak_http_${r.status}`);return d}
async function claimOrder(db:any,input:any){const q=await db.rpc("dlavie_digital_claim_order",input);if(q.error)throw q.error;const claim=q.data?.[0];if(!claim?.order_id)throw new Error("order_claim_failed");if(claim.created!==false){const sq=await db.from("dlavie_digital_orders").update({source:"iak"}).eq("id",claim.order_id);if(sq.error)throw sq.error}const oq=await db.from("dlavie_digital_orders").select("*").eq("id",claim.order_id).single();if(oq.error)throw oq.error;return{order:oq.data,created:claim.created!==false}}
function extType(p:any){const x=`${p.category||""} ${p.product_type||""} ${p.product_name||""} ${p.sku||""}`.toLowerCase();if(x.includes("samsat")||x.includes("pajak kendaraan")||x.includes("pajakkendaraan"))return"samsat";if(x.includes("e-money")||x.includes("emoney"))return"emoney";return"unknown"}
Deno.serve(withSupabase({auth:"none"},async(req,ctx)=>{const headers=cors();if(req.method==="OPTIONS")return new Response(null,{status:204,headers});if(req.method!=="POST")return Response.json({error:"method_not_allowed"},{status:405,headers});try{const b:any=await readBody(req),action=safe(b.action,40),db=ctx.supabaseAdmin.schema("api");if(action!=="inquiry")return Response.json({error:"invalid_action"},{status:400,headers});const token=safe(b.wallet_token,180),userId=safe(b.user_id,80),wallet=await authWallet(db,token);if(!wallet||!userId)return Response.json({error:"auth_required"},{status:401,headers});const s=await settings(db);if(!s.live_enabled||!s.postpaid_enabled)return Response.json({error:"postpaid_disabled"},{status:409,headers});const [username,key]=await Promise.all([vault(db,"dlavie_iak_username"),vault(db,s.environment==="production"?"dlavie_iak_production_api_key":"dlavie_iak_sandbox_api_key")]);if(!username||!key)throw new Error("integration_not_ready");const sku=safe(b.sku,160);let customer=safe(b.customer_no,220);if(!sku||customer.length<3)return Response.json({error:"invalid_target"},{status:400,headers});const pq=await db.from("dlavie_digital_products").select("*").eq("source","iak").eq("sku",sku).eq("product_kind","postpaid").eq("buyer_product_status",true).eq("seller_product_status",true).maybeSingle();if(pq.error)throw pq.error;const p:any=pq.data;if(!p)return Response.json({error:"product_unavailable"},{status:409,headers});const type=extType(p);if(!p.requires_extended_input||type==="unknown")return Response.json({error:"extended_input_not_applicable"},{status:409,headers});const payload:any={commands:"inq-pasca",username,code:p.sku};if(type==="emoney"){const amount=Math.round(Number(b.amount||0));if(!Number.isFinite(amount)||amount<1000||amount>100000000)return Response.json({error:"invalid_amount"},{status:400,headers});payload.hp=customer;payload.desc={amount}}else{const parts=customer.split(",").map((x:string)=>x.trim()).filter(Boolean);if(parts.length!==2||parts.some((x:string)=>x.length<4))return Response.json({error:"invalid_samsat_target"},{status:400,headers});payload.hp=parts[0];payload.nomor_identitas=parts[1];customer=`${parts[0]},${parts[1]}`}
const claim=await claimOrder(db,{p_wallet_id:wallet.id,p_user_id:userId,p_product_kind:"postpaid",p_sku:p.sku,p_product_name:p.product_name,p_category:p.category,p_brand:p.brand,p_product_type:p.product_type||"",p_customer_no:customer,p_base_price:0,p_sell_price:0,p_environment:s.environment,p_ref_id:refId(),p_dedupe_seconds:30});const order:any=claim.order,ref=String(order.ref_id);if(!claim.created)return Response.json({ok:true,duplicate:true,order,balance:await walletBalance(db,wallet.id)},{headers});payload.ref_id=ref;payload.sign=md5(username+key+ref);const base=s.environment==="production"?"https://mobilepulsa.net":"https://testpostpaid.mobilepulsa.net",raw=await post(`${base}/api/v1/bill/check`,payload),data=raw?.data||{};if(String(data.response_code)!=="00"){const uq=await db.from("dlavie_digital_orders").update({source:"iak",status:"failed",supplier_status:"inquiry_failed",rc:safe(data.response_code,50)||null,message:safe(data.message||"Inquiry tagihan gagal."),raw_response:{...raw,extended_input:type},gateway_forwarded:true,updated_at:new Date().toISOString()}).eq("id",order.id).select("*").single();return Response.json({ok:false,error:"inquiry_failed",message:uq.data?.message,order:uq.data},{status:409,headers})}const price=Math.max(0,Math.round(Number(data.price||0))),total=sell(price,s);if(total<=0)return Response.json({error:"invalid_inquiry_amount"},{status:502,headers});const detail=(data.desc&&typeof data.desc==="object")?{...data.desc,_dlavie_extended_type:type,...(type==="emoney"?{_dlavie_amount:payload.desc.amount}:{}),...(type==="samsat"?{_dlavie_identity:payload.nomor_identitas}:{})}:data.desc||{};const patch:any={source:"iak",status:"inquired",supplier_request_id:safe(data.tr_id,120),customer_name:safe(data.tr_name,220)||null,period:safe(data.period,240)||null,base_price:Number.isFinite(Number(data.selling_price))?Math.round(Number(data.selling_price)):price,sell_price:total,inquiry_admin:Number.isFinite(Number(data.admin))?Math.round(Number(data.admin)):null,inquiry_price:price,inquiry_selling_price:Number.isFinite(Number(data.selling_price))?Math.round(Number(data.selling_price)):null,inquiry_detail:detail,inquired_at:new Date().toISOString(),inquiry_valid_until:jakartaEndOfDay(),supplier_status:"inquiry_success",rc:safe(data.response_code,50),message:safe(data.message),raw_response:{...raw,extended_input:type},gateway_forwarded:true,updated_at:new Date().toISOString()};const uq=await db.from("dlavie_digital_orders").update(patch).eq("id",order.id).select("*").single();if(uq.error)throw uq.error;return Response.json({ok:true,order:uq.data,balance:await walletBalance(db,wallet.id)},{headers})}catch(e){console.error("dlavie-digital-market-iak-extended",e);const m=e instanceof Error?e.message:"iak_extended_error";return Response.json({error:m,message:m},{status:m==="integration_not_ready"?503:500,headers:cors()})}}));
