import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "npm:@supabase/server";
import { createHash } from "node:crypto";

const ORIGIN="https://drmacze.github.io";
const cors=()=>({"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"});
async function body(req:Request){const t=(req.headers.get("content-type")||"").toLowerCase();if(t.includes("application/x-www-form-urlencoded"))return Object.fromEntries(new URLSearchParams(await req.text()).entries());return await req.json().catch(()=>({}))}
function safe(v:unknown,n=500){return String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,n)}
function md5(v:string){return createHash("md5").update(v).digest("hex")}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
async function secret(db:any,name:string){const q=await db.rpc("dlavie_get_vault_secret",{p_name:name});if(q.error)throw q.error;return String(q.data||"")}
async function setSecret(db:any,name:string,value:string){const q=await db.rpc("dlavie_set_vault_secret",{p_name:name,p_value:value});if(q.error)throw q.error}
async function auth(db:any,token:string){if(!token)return null;const q=await db.from("dlavie_assistant_admin_sessions").select("admin_name,expires_at").eq("token_hash",await sha256(token)).maybeSingle();if(q.error)throw q.error;if(!q.data||new Date(q.data.expires_at).getTime()<=Date.now())return null;return q.data}
async function settings(db:any){const q=await db.from("dlavie_iak_settings").select("*").eq("id",1).single();if(q.error)throw q.error;return q.data}
function bases(env:string){return env==="production"?{prepaid:"https://prepaid.iak.id",postpaid:"https://mobilepulsa.net"}:{prepaid:"https://prepaid.iak.dev",postpaid:"https://testpostpaid.mobilepulsa.net"}}
async function creds(db:any,env:string){const [username,sandboxKey,productionKey]=await Promise.all([secret(db,"dlavie_iak_username"),secret(db,"dlavie_iak_sandbox_api_key"),secret(db,"dlavie_iak_production_api_key")]);return{username,key:env==="production"?productionKey:sandboxKey,sandboxKey,productionKey}}
async function post(url:string,payload:any){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`iak_http_${r.status}`);return d}
function sell(base:number,s:any){const min=Math.max(0,Number(s.minimum_markup||0)),v=Number(s.markup_value||0),m=s.markup_mode==="percent"?Math.max(min,Math.round(base*v/100)):Math.max(min,Math.round(v));return Math.max(base,base+m)}
function compact(...values:unknown[]){return values.map(v=>safe(v,300)).join(" ").toLowerCase().replace(/[^a-z0-9]+/g,"")}
function normalize(kind:string,rawCategory:string,brand:string,name:string,type:string,sku:string){const all=compact(rawCategory,brand,name,type,sku),cat=compact(rawCategory),typ=compact(type),br=compact(brand);if(kind==="postpaid"){if(typ.includes("pajakkendaraan")||all.includes("samsat"))return"SAMSAT";if(typ==="pbb"||all.includes("pajakbumibangunan"))return"PBB";if(typ==="bpjs"||all.includes("bpjs"))return"BPJS";if(typ==="pdam")return"PDAM";if(typ==="pln")return"PLN & Listrik";if(typ==="emoney")return"E-Money";if(typ==="internet"||typ==="tv")return"Internet & TV";if(typ==="finance")return"Multifinance";if(typ==="gas")return"Gas";if(typ.includes("pajak"))return"Pajak";if(typ==="hp")return"Telepon Pascabayar";if(typ==="asuransi")return"Asuransi";return"Tagihan Lainnya"}if(cat==="pulsa"||typ==="pulsa"||all.includes("pulsa"))return"Pulsa";if(cat==="data"||typ==="data"||all.includes("paketdata")||all.includes("kuota"))return"Paket Data";if(cat==="pln"||typ==="pln"||all.includes("tokenpln"))return"PLN";if(cat==="emoney"||typ==="emoney"||["dana","ovo","gopay","shopeepay","linkaja"].some(x=>br.includes(x)))return"E-Wallet";if(cat==="game"||cat==="games"||cat==="voucher"||typ.includes("game")||typ.includes("voucher"))return"Voucher & Game";return rawCategory||"Produk Digital Lainnya"}
function extended(kind:string,type:string,name:string,sku:string){if(kind!=="postpaid")return false;const x=compact(type,name,sku);return x.includes("emoney")||x.includes("samsat")||x.includes("pajakkendaraan")}

Deno.serve(withSupabase({auth:"none"},async(req,ctx)=>{const headers=cors();if(req.method==="OPTIONS")return new Response(null,{status:204,headers});if(req.method!=="POST")return Response.json({error:"method_not_allowed"},{status:405,headers});try{const b:any=await body(req),db=ctx.supabaseAdmin.schema("api"),admin=await auth(db,safe(b.admin_token,180));if(!admin)return Response.json({error:"admin_auth_required"},{status:401,headers});const action=safe(b.action,40),s=await settings(db),c=await creds(db,s.environment);
if(action==="status"){const credentials=!!c.username&&!!c.key,catalog=Number(s.catalog_count||0)>0;return Response.json({ok:true,settings:s,secrets:{username:!!c.username,sandbox_api_key:!!c.sandboxKey,production_api_key:!!c.productionKey},readiness:{credentials,catalog,testing_safe:!!c.username&&!!c.sandboxKey&&catalog,production_safe:!!c.username&&!!c.productionKey&&catalog},callback_url:"https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-iak-callback",admin_name:admin.admin_name},{headers})}
if(action==="save_credentials"){const username=safe(b.username,100),sandbox=safe(b.sandbox_api_key,400),production=safe(b.production_api_key,400);if(username.length<4)return Response.json({error:"invalid_username"},{status:400,headers});await setSecret(db,"dlavie_iak_username",username);if(sandbox)await setSecret(db,"dlavie_iak_sandbox_api_key",sandbox);if(production)await setSecret(db,"dlavie_iak_production_api_key",production);return Response.json({ok:true},{headers})}
if(action==="save_settings"){const env=safe(b.environment,20)==="production"?"production":"testing",mode=safe(b.markup_mode,20)==="percent"?"percent":"fixed",value=Math.max(0,Number(b.markup_value||0)),minimum=Math.max(0,Math.round(Number(b.minimum_markup||0))),enabled=String(b.live_enabled)==="true",postpaid=String(b.postpaid_enabled)==="true";const cc=await creds(db,env);if(enabled&&(!cc.username||!cc.key||Number(s.catalog_count||0)<=0))return Response.json({error:"market_not_ready",message:"IAK membutuhkan username, API key environment aktif, dan katalog tersinkron sebelum transaksi dibuka."},{status:409,headers});const q=await db.from("dlavie_iak_settings").update({environment:env,markup_mode:mode,markup_value:value,minimum_markup:minimum,live_enabled:enabled,postpaid_enabled:postpaid,updated_at:new Date().toISOString()}).eq("id",1).select("*").single();if(q.error)throw q.error;return Response.json({ok:true,settings:q.data},{headers})}
if(action==="test_connection"){if(!c.username||!c.key)return Response.json({error:"credentials_required"},{status:409,headers});const base=bases(s.environment),sign=md5(c.username+c.key+"pl"),d=await post(`${base.prepaid}/api/pricelist`,{username:c.username,sign,status:"active"}),rows=Array.isArray(d?.data?.pricelist)?d.data.pricelist:Array.isArray(d?.data)?d.data:Array.isArray(d?.pricelist)?d.pricelist:[];return Response.json({ok:true,count:rows.length,message:`IAK ${s.environment} terhubung.`},{headers})}
if(action==="sync_catalog"){if(!c.username||!c.key)return Response.json({error:"credentials_required"},{status:409,headers});const started=new Date().toISOString(),base=bases(s.environment),sign=md5(c.username+c.key+"pl");try{const prepaid=await post(`${base.prepaid}/api/pricelist`,{username:c.username,sign,status:"all"}),preRows=Array.isArray(prepaid?.data?.pricelist)?prepaid.data.pricelist:Array.isArray(prepaid?.data)?prepaid.data:Array.isArray(prepaid?.pricelist)?prepaid.pricelist:[];const mapped:any[]=[];for(const x of preRows){const sku=safe(x.product_code||x.pulsa_code,160),brand=safe(x.product_description||x.pulsa_op,160)||"Lainnya",nom=safe(x.product_nominal||x.pulsa_nominal,180),name=nom&&nom!=="-"?`${brand} ${nom}`:brand,type=safe(x.product_type||x.pulsa_type,120),rawCat=safe(x.product_category||x.pulsa_category,120)||type,price=Math.max(0,Math.round(Number(x.product_price??x.pulsa_price??0))),active=String(x.status||"").toLowerCase()==="active";if(!sku)continue;mapped.push({source:"iak",product_kind:"prepaid",sku,product_name:name,category:normalize("prepaid",rawCat,brand,name,type,sku),brand,product_type:type||null,seller_name:"IAK",base_price:price,sell_price:sell(price,s),admin_fee:null,commission:null,buyer_product_status:active,seller_product_status:active,unlimited_stock:true,stock:0,multi:true,start_cut_off:null,end_cut_off:null,description:safe(x.product_details||x.pulsa_details,1200)||null,requires_extended_input:false,raw:x,synced_at:started,updated_at:started})}
if(s.postpaid_enabled){const pasca=await post(`${base.postpaid}/api/v1/bill/check`,{commands:"pricelist-pasca",username:c.username,sign,status:"all"}),pascaRows=Array.isArray(pasca?.data?.pasca)?pasca.data.pasca:Array.isArray(pasca?.data)?pasca.data:[];for(const x of pascaRows){const sku=safe(x.code,160),name=safe(x.name,220)||sku,type=safe(x.type,120),active=Number(x.status)===1,fee=Math.max(0,Math.round(Number(x.fee||0))),commission=Math.max(0,Math.round(Number(x.komisi||0)));if(!sku)continue;mapped.push({source:"iak",product_kind:"postpaid",sku,product_name:name,category:normalize("postpaid",safe(x.category,120),name,name,type,sku),brand:name,product_type:type||null,seller_name:"IAK",base_price:0,sell_price:0,admin_fee:fee,commission,buyer_product_status:active,seller_product_status:active,unlimited_stock:true,stock:0,multi:false,start_cut_off:null,end_cut_off:null,description:null,requires_extended_input:extended("postpaid",type,name,sku),raw:x,synced_at:started,updated_at:started})}}
for(let i=0;i<mapped.length;i+=300){const uq=await db.from("dlavie_digital_products").upsert(mapped.slice(i,i+300),{onConflict:"sku"});if(uq.error)throw uq.error}const stale=await db.from("dlavie_digital_products").update({buyer_product_status:false,seller_product_status:false,updated_at:started}).eq("source","iak").lt("synced_at",started);if(stale.error)throw stale.error;const cq=await db.from("dlavie_digital_products").select("id",{count:"exact",head:true}).eq("source","iak").eq("buyer_product_status",true).eq("seller_product_status",true);if(cq.error)throw cq.error;const count=Number(cq.count||0);const sq=await db.from("dlavie_iak_settings").update({catalog_count:count,last_catalog_sync_at:started,last_catalog_sync_status:"success",last_catalog_sync_message:`${count} SKU IAK aktif tersinkron`,updated_at:new Date().toISOString()}).eq("id",1).select("*").single();if(sq.error)throw sq.error;return Response.json({ok:true,count,settings:sq.data},{headers})}catch(e){const msg=e instanceof Error?e.message:"sync_failed";await db.from("dlavie_iak_settings").update({last_catalog_sync_at:started,last_catalog_sync_status:"failed",last_catalog_sync_message:msg,updated_at:new Date().toISOString()}).eq("id",1);throw e}}
return Response.json({error:"invalid_action"},{status:400,headers})}catch(e){console.error("dlavie-iak-admin",e);const msg=e instanceof Error?e.message:"iak_admin_error";return Response.json({error:msg,message:msg},{status:500,headers:cors()})}}));
