import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "npm:@supabase/server";

const ORIGIN="https://drmacze.github.io";
const BASE="https://api.h2h.id/api/trx";
const CALLBACK="https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-h2h-callback";
const cors=()=>({"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"});
const safe=(v:unknown,n=700)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,n);
async function parseBody(req:Request){const t=(req.headers.get("content-type")||"").toLowerCase();if(t.includes("application/x-www-form-urlencoded"))return Object.fromEntries(new URLSearchParams(await req.text()).entries());return await req.json().catch(()=>({}));}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
async function getSecret(db:any,name:string){const q=await db.rpc("dlavie_get_vault_secret",{p_name:name});if(q.error)throw q.error;return String(q.data||"");}
async function setSecret(db:any,name:string,value:string){const q=await db.rpc("dlavie_set_vault_secret",{p_name:name,p_value:value});if(q.error)throw q.error;}
async function auth(db:any,token:string){if(!token)return null;const q=await db.from("dlavie_assistant_admin_sessions").select("admin_name,expires_at").eq("token_hash",await sha256(token)).maybeSingle();if(q.error)throw q.error;if(!q.data||new Date(q.data.expires_at).getTime()<=Date.now())return null;return q.data;}
async function settings(db:any){const q=await db.from("dlavie_h2h_settings").select("*").eq("id",1).single();if(q.error)throw q.error;return q.data;}
async function creds(db:any){const [memberID,pin,password,webhookKey]=await Promise.all([getSecret(db,"dlavie_h2h_member_id"),getSecret(db,"dlavie_h2h_pin"),getSecret(db,"dlavie_h2h_password"),getSecret(db,"dlavie_h2h_webhook_key")]);return{memberID,pin,password,webhookKey};}
async function h2h(path:string,c:any,extra:Record<string,string>={}){if(!c.memberID||!c.pin||!c.password)throw new Error("credentials_required");const u=new URL(`${BASE}${path}`);u.searchParams.set("memberID",c.memberID);u.searchParams.set("pin",c.pin);u.searchParams.set("password",c.password);for(const[k,v]of Object.entries(extra))if(v!=="")u.searchParams.set(k,v);const r=await fetch(u,{headers:{accept:"application/json"}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`h2h_http_${r.status}`);if(d?.status!==true)throw new Error(safe(d?.message,500)||"h2h_request_failed");return d;}
function extractRows(d:any){const c=[d?.data,d?.data?.products,d?.data?.items,d?.data?.pricelist,d?.products,d?.items,d?.pricelist];for(const x of c)if(Array.isArray(x))return x;if(d?.data&&typeof d.data==="object"){const arrays=Object.values(d.data).filter(Array.isArray) as any[];if(arrays.length)return arrays.flat();}return[];}
function rowObject(raw:any){if(raw&&typeof raw==="object"&&!Array.isArray(raw)){if(raw.product&&typeof raw.product==="object")return{...raw.product,...raw};if(raw.item&&typeof raw.item==="object")return{...raw.item,...raw};return raw;}return{};}
function first(...vals:any[]){for(const v of vals){if(v!==undefined&&v!==null&&String(v).trim()!=="")return v;}return null;}
function skuOf(raw:any){const x=rowObject(raw);return safe(first(x.code,x.product_code,x.productCode,x.buyer_sku_code,x.buyerSkuCode,x.sku,x.sku_code,x.skuCode,x.product_sku,x.productSku,x.kode,x.kode_produk,x.kodeProduk),180);}
function nameOf(raw:any,sku:string){const x=rowObject(raw);return safe(first(x.name,x.product_name,x.productName,x.product,x.title,x.nama,x.nama_produk,x.namaProduk),260)||sku;}
function operatorOf(raw:any){const x=rowObject(raw);return safe(first(x.operator,x.brand,x.seller_name,x.sellerName,x.provider,x.vendor,x.category_name,x.categoryName),180)||"H2H.id";}
function priceOf(raw:any){const x=rowObject(raw);const v=Number(first(x.price,x.sell_price,x.sellPrice,x.seller_price,x.sellerPrice,x.base_price,x.basePrice,x.harga,x.amount,0));return Number.isFinite(v)?Math.max(0,Math.round(v)):0;}
function isOpen(raw:any){const x=rowObject(raw);const bool=first(x.buyer_product_status,x.buyerProductStatus,x.seller_product_status,x.sellerProductStatus,x.active,x.is_active,x.isActive);if(typeof bool==="boolean")return bool;const status=safe(first(x.status,x.product_status,x.productStatus,"OPEN"),50).toUpperCase();const provider=safe(first(x.provider_status,x.providerStatus,"active"),50).toLowerCase();return !["CLOSED","OFF","INACTIVE","FALSE","0"].includes(status)&&provider!=="inactive";}
function descriptionOf(raw:any){const x=rowObject(raw);return safe(first(x.description,x.desc,x.keterangan,x.note),1400)||null;}
function markup(base:number,s:any){const min=Math.max(0,Number(s.minimum_markup||0)),v=Math.max(0,Number(s.markup_value||0));const m=s.markup_mode==="percent"?Math.max(min,Math.round(base*v/100)):Math.max(min,Math.round(v));return Math.max(base,base+m);}
function postpaidCategory(name:string,operator:string){const x=`${name} ${operator}`.toLowerCase();if(x.includes("bpjs"))return"BPJS";if(x.includes("pdam")||x.includes("air"))return"PDAM";if(x.includes("pln")||x.includes("listrik"))return"PLN & Listrik";if(x.includes("telkom")||x.includes("indihome")||x.includes("internet")||x.includes("tv"))return"Internet & TV";if(x.includes("pbb")||x.includes("pajak bumi"))return"PBB";if(x.includes("samsat")||x.includes("kendaraan"))return"SAMSAT";if(x.includes("finance")||x.includes("leasing")||x.includes("multifinance"))return"Multifinance";if(x.includes("gas")||x.includes("pgn"))return"Gas";if(x.includes("asuransi"))return"Asuransi";return"Tagihan Lainnya";}
function category(type:string,name:string,operator:string){if(type==="pulsa")return"Pulsa";if(type==="paket_data"||type==="paket_telp_sms")return"Paket Data";if(type==="pln")return"PLN";if(type==="voucher_game"||type==="cetak_voucher")return"Voucher & Game";if(type==="e_wallet"||type==="nominal_bebas")return"E-Wallet";if(type==="streaming")return"Voucher & Streaming";if(type==="pascabayar"||type==="tagihan")return postpaidCategory(name,operator);return"Produk Digital Lainnya";}
function inferType(raw:any){const x=rowObject(raw);const explicit=safe(first(x.type,x.product_type,x.productType,x.category_type,x.categoryType),60).toLowerCase();if(explicit)return explicit;const t=`${nameOf(x,"")} ${operatorOf(x)} ${descriptionOf(x)||""}`.toLowerCase();if(t.includes("pulsa"))return"pulsa";if(t.includes("paket data")||t.includes("kuota")||t.includes("internet"))return"paket_data";if(t.includes("pln")||t.includes("token listrik"))return"pln";if(t.includes("dana")||t.includes("ovo")||t.includes("gopay")||t.includes("shopeepay")||t.includes("linkaja"))return"e_wallet";if(t.includes("mobile legends")||t.includes("free fire")||t.includes("pubg")||t.includes("game"))return"voucher_game";if(t.includes("netflix")||t.includes("spotify")||t.includes("vidio")||t.includes("streaming"))return"streaming";return"lainnya";}
function sampleShape(rows:any[]){const x=rows?.[0];if(Array.isArray(x))return{kind:"array",length:x.length};if(x&&typeof x==="object")return{kind:"object",keys:Object.keys(x).slice(0,30),nested_product_keys:x.product&&typeof x.product==="object"?Object.keys(x.product).slice(0,20):[]};return{kind:typeof x};}

Deno.serve(withSupabase({auth:"none"},async(req,ctx)=>{const headers=cors();if(req.method==="OPTIONS")return new Response(null,{status:204,headers});if(req.method!=="POST")return Response.json({error:"method_not_allowed"},{status:405,headers});try{const b:any=await parseBody(req);const db=ctx.supabaseAdmin.schema("api");const admin=await auth(db,safe(b.admin_token,180));if(!admin)return Response.json({error:"admin_auth_required"},{status:401,headers});const action=safe(b.action,40),s=await settings(db),c=await creds(db);
if(action==="status"){const credentials=!!c.memberID&&!!c.pin&&!!c.password,catalog=Number(s.catalog_count||0)>0;return Response.json({ok:true,settings:s,secrets:{member_id:!!c.memberID,pin:!!c.pin,password:!!c.password,webhook_key:!!c.webhookKey},readiness:{credentials,catalog,ready:credentials&&catalog&&!!c.webhookKey},callback_url:CALLBACK,admin_name:admin.admin_name},{headers});}
if(action==="save_credentials"){const memberID=safe(b.member_id,100),pin=safe(b.pin,40),password=safe(b.password,300);if(memberID.length<2)return Response.json({error:"invalid_member_id"},{status:400,headers});if(pin.length<4||pin.length>20)return Response.json({error:"invalid_pin"},{status:400,headers});if(password.length<4)return Response.json({error:"invalid_h2h_password"},{status:400,headers});await Promise.all([setSecret(db,"dlavie_h2h_member_id",memberID),setSecret(db,"dlavie_h2h_pin",pin),setSecret(db,"dlavie_h2h_password",password)]);await db.from("dlavie_h2h_settings").update({live_enabled:false,catalog_count:0,last_catalog_sync_status:null,last_catalog_sync_message:"Credential berubah; sync katalog ulang."}).eq("id",1);return Response.json({ok:true},{headers});}
if(action==="save_webhook_secret"){const value=safe(b.webhook_secret,500);if(value.length<16)return Response.json({error:"invalid_webhook_secret",message:"Webhook Secret/Secret Key H2H terlalu pendek."},{status:400,headers});await setSecret(db,"dlavie_h2h_webhook_key",value);await db.from("dlavie_h2h_settings").update({webhook_configured:true}).eq("id",1);return Response.json({ok:true},{headers});}
if(action==="test_connection"){const d=await h2h("/balance",c),balance=Math.max(0,Math.round(Number(d?.data?.balance||0))),verification=d?.data?.verification||null;await db.from("dlavie_h2h_settings").update({last_hcoin_balance:balance,last_verification:verification}).eq("id",1);return Response.json({ok:true,balance,verification,message:"H2H.id terhubung."},{headers});}
if(action==="save_settings"){const mode=safe(b.markup_mode,20)==="percent"?"percent":"fixed",value=Math.max(0,Number(b.markup_value||0)),minimum=Math.max(0,Math.round(Number(b.minimum_markup||0))),live=String(b.live_enabled)==="true",postpaid=String(b.postpaid_enabled)==="true";if(!Number.isFinite(value)||value>1000000||minimum>1000000)return Response.json({error:"invalid_markup"},{status:400,headers});const changed=mode!==s.markup_mode||Number(value)!==Number(s.markup_value)||minimum!==Number(s.minimum_markup)||postpaid!==!!s.postpaid_enabled;if(live&&(!c.memberID||!c.pin||!c.password||!c.webhookKey||Number(s.catalog_count||0)<=0))return Response.json({error:"market_not_ready",message:"Simpan credential, Webhook Secret H2H, dan sync katalog sebelum mengaktifkan transaksi."},{status:409,headers});const patch:any={markup_mode:mode,markup_value:value,minimum_markup:minimum,live_enabled:changed?false:live,postpaid_enabled:postpaid};if(changed){patch.catalog_count=0;patch.last_catalog_sync_status=null;patch.last_catalog_sync_message="Pengaturan harga/produk berubah; sync katalog ulang.";}const q=await db.from("dlavie_h2h_settings").update(patch).eq("id",1).select("*").single();if(q.error)throw q.error;return Response.json({ok:true,settings:q.data,catalog_reset:changed},{headers});}
if(action==="sync_catalog"){if(!c.memberID||!c.pin||!c.password)return Response.json({error:"credentials_required"},{status:409,headers});const started=new Date().toISOString();const types=s.postpaid_enabled?["pulsa","paket_data","pln","voucher_game","e_wallet","streaming","paket_telp_sms","cetak_voucher","pascabayar","tagihan"]:["pulsa","paket_data","pln","voucher_game","e_wallet","streaming","paket_telp_sms","cetak_voucher"];try{const mapped:any[]=[];const stats:Record<string,number>={};let sample:any=null;const pushRows=(rows:any[],type:string)=>{stats[type]=(stats[type]||0)+rows.length;if(!sample&&rows.length)sample=sampleShape(rows);for(const raw of rows){const sku=skuOf(raw);if(!sku)continue;const x=rowObject(raw),name=nameOf(x,sku),operator=operatorOf(x),price=priceOf(x),open=isOpen(x),kind=(type==="pascabayar"||type==="tagihan")?"postpaid":"prepaid";mapped.push({source:"h2h",product_kind:kind,sku,product_name:name,category:category(type,name,operator),brand:operator,product_type:type,seller_name:"H2H.id",base_price:price,sell_price:kind==="prepaid"?markup(price,s):0,admin_fee:null,commission:null,buyer_product_status:open,seller_product_status:open,unlimited_stock:true,stock:0,multi:true,start_cut_off:null,end_cut_off:null,description:descriptionOf(x),requires_extended_input:false,raw:{...x,_dlavie_h2h_type:type},synced_at:started,updated_at:started});}};
for(const type of types){const d=await h2h("/pricelist",c,{type});pushRows(extractRows(d),type);}if(mapped.length===0){const d=await h2h("/pricelist",c);const rows=extractRows(d);stats._fallback_unfiltered=rows.length;if(!sample&&rows.length)sample=sampleShape(rows);for(const raw of rows){const type=inferType(raw);if(!s.postpaid_enabled&&(type==="pascabayar"||type==="tagihan"))continue;pushRows([raw],type);}}if(mapped.length===0)throw new Error(`catalog_empty: ${Object.values(stats).reduce((a,b)=>a+b,0)} item diterima tetapi SKU tidak dikenali. sample=${JSON.stringify(sample)} stats=${JSON.stringify(stats)}`);
const uniq=new Map<string,any>();for(const row of mapped)uniq.set(row.sku,row);const rows=[...uniq.values()];for(let i=0;i<rows.length;i+=250){const uq=await db.from("dlavie_digital_products").upsert(rows.slice(i,i+250),{onConflict:"sku"});if(uq.error)throw uq.error;}const stale=await db.from("dlavie_digital_products").update({buyer_product_status:false,seller_product_status:false,updated_at:started}).eq("source","h2h").lt("synced_at",started);if(stale.error)throw stale.error;const cq=await db.from("dlavie_digital_products").select("id",{count:"exact",head:true}).eq("source","h2h").eq("buyer_product_status",true).eq("seller_product_status",true);if(cq.error)throw cq.error;const count=Number(cq.count||0);if(count<=0)throw new Error(`catalog_no_active_sku: ${rows.length} item terbaca tetapi tidak ada SKU aktif.`);const sq=await db.from("dlavie_h2h_settings").update({catalog_count:count,last_catalog_sync_at:started,last_catalog_sync_status:"success",last_catalog_sync_message:`${count} SKU H2H.id aktif tersinkron`}).eq("id",1).select("*").single();if(sq.error)throw sq.error;return Response.json({ok:true,count,stats,settings:sq.data},{headers});}catch(e){const msg=e instanceof Error?e.message:"sync_failed";await db.from("dlavie_h2h_settings").update({catalog_count:0,last_catalog_sync_at:started,last_catalog_sync_status:"failed",last_catalog_sync_message:safe(msg,650)}).eq("id",1);throw e;}}
return Response.json({error:"invalid_action"},{status:400,headers});}catch(e){console.error("dlavie-h2h-admin",e instanceof Error?e.message:e);const msg=e instanceof Error?e.message:"h2h_admin_error";return Response.json({error:msg,message:msg},{status:500,headers:cors()});}}));
