import type { DigitalOrder } from './digital-market-api'
import { digitalStatus, money, when } from './digital-market-api'
import { maskPhone } from './DigitalPhoneIntelligence'

const mask=(v='')=>{if(!v)return'—';if(/^\+?\d{8,}$/.test(v.replace(/\s/g,'')))return maskPhone(v);if(v.length<7)return'••••';return `${v.slice(0,3)}••••${v.slice(-3)}`}
const maskSn=(v='')=>v.length<9?'••••••':`${v.slice(0,4)}••••••${v.slice(-4)}`

export default function DigitalOrderHistory({open,orders,busy,onClose,onCheck,onPay,onReceipt}:{open:boolean;orders:DigitalOrder[];busy:boolean;onClose:()=>void;onCheck:(ref:string)=>void;onPay?:(ref:string)=>void;onReceipt?:(order:DigitalOrder)=>void}){
  if(!open)return null
  return <div className="dlv-digital-history-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="dlv-digital-history"><header><div><span>PESANAN DIGITAL</span><h2>Riwayat pembelian</h2><p>Nomor tujuan dan SN disamarkan. Buka Struk untuk melihat bukti lengkap.</p></div><button onClick={onClose}>×</button></header>{orders.length?orders.map(o=><article key={o.ref_id}><div className="dlv-history-copy"><small>{o.product_kind==='postpaid'?'TAGIHAN · ':''}{o.category} · {o.brand}</small><strong>{o.product_name}</strong><code>{o.ref_id}</code></div><div className="dlv-history-state"><b>{money.format(o.sell_price)}</b><em data-status={o.status}>{digitalStatus(o.status)}</em><small>{when(o.created_at)}</small></div>{o.customer_no&&<p><b>Tujuan</b><span>{mask(o.customer_no)}</span></p>}{o.customer_name&&<p><b>Pelanggan</b><span>{o.customer_name}</span></p>}{o.period&&<p><b>Periode</b><span>{o.period}</span></p>}{o.serial_number&&<p><b>SN / TOKEN</b><span>{maskSn(o.serial_number)}</span></p>}{o.message&&<p className="is-message">{o.message}</p>}<div className="dlv-history-actions">{onReceipt&&<button className="is-receipt" onClick={()=>onReceipt(o)}>▣ Struk</button>}{o.status==='inquired'&&onPay&&<button className="is-pay" disabled={busy} onClick={()=>onPay(o.ref_id)}>Bayar tagihan</button>}{(o.status==='pending'||o.status==='reserved')&&<button disabled={busy} onClick={()=>onCheck(o.ref_id)}>Cek status</button>}</div></article>):<div className="dlv-history-empty">Belum ada pembelian produk digital.</div>}</aside></div>
}
