import { useEffect, useMemo, useState } from 'react'

type LegalTab='terms'|'privacy'|'refund'|'acceptable'|'disclosure'
type FAQ={q:string;a:string;tags:string[]}
type Section={title:string;paragraphs?:string[];bullets?:string[]}
type Doc={title:string;intro:string;sections:Section[]}
type Profile={id?:string;username?:string}

const UPDATED_ID='19 Agustus 2026'
const UPDATED_EN='19 August 2026'
const PROFILE_KEY='dlavie-account-profile-v1'

function english(){return localStorage.getItem('dlavie-language')==='en'}
function profile():Profile|null{try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'null') as Profile|null}catch{return null}}

const faqId:FAQ[]=[
 {q:'Apa itu DLavie sekarang?',a:'DLavie adalah marketplace produk digital dengan satu Wallet untuk Pulsa, Paket Data, PLN, E-Wallet, Voucher & Game, pembayaran tagihan, serta Nomor Virtual sebagai layanan tambahan. Katalog produk digital disiapkan untuk terhubung ke supplier melalui backend DLavie.',tags:['dasar','market','digital']},
 {q:'Produk apa saja yang tersedia di Digital Market?',a:'Kategori utama mencakup Pulsa, Paket Data, PLN/token listrik, E-Wallet, Voucher & Game, serta layanan pascabayar/tagihan ketika diaktifkan. Kategori dan SKU aktual mengikuti katalog supplier yang sedang aktif dan tersinkron.',tags:['produk','katalog','supplier']},
 {q:'Mengapa kartu produk menampilkan SYNC atau 0 SKU?',a:'Itu berarti UI kategori sudah tersedia tetapi katalog supplier belum tersinkron atau transaksi supplier belum diaktifkan. DLavie tidak membuat produk atau harga palsu ketika katalog backend masih kosong.',tags:['sync','sku','supplier','digiflazz']},
 {q:'Bagaimana alur membeli produk prabayar?',a:'Isi Wallet, pilih kategori dan produk, masukkan tujuan dengan teliti, lalu konfirmasi pembayaran. Backend memverifikasi saldo, membuat reference order, meneruskan transaksi ke supplier saat integrasi aktif, dan menyimpan status hingga sukses, gagal, atau direfund.',tags:['prepaid','pulsa','data','wallet']},
 {q:'Bagaimana alur Bayar Tagihan?',a:'Untuk produk pascabayar, DLavie melakukan inquiry terlebih dahulu. Periksa nama pelanggan, periode, detail dan total tagihan sebelum menekan Bayar. Saldo baru dipotong pada tahap pembayaran, bukan saat inquiry.',tags:['postpaid','tagihan','inquiry']},
 {q:'Apa arti Pending, Sukses, Gagal, dan Refunded?',a:'Pending berarti supplier belum memberi hasil final. Sukses berarti supplier mengonfirmasi transaksi berhasil. Gagal berarti transaksi tidak berhasil dan saldo harus dipulihkan sesuai ledger/refund. Refunded berarti pengembalian dana ke Wallet telah dicatat.',tags:['status','pending','refund']},
 {q:'Di mana saya melihat token PLN, serial number, atau hasil produk?',a:'Hasil supplier seperti SN/token ditampilkan pada receipt dan riwayat order ketika tersedia. Simpan reference ID transaksi untuk pengecekan status dan bantuan.',tags:['pln','token','sn','receipt']},
 {q:'Berapa minimum deposit Wallet?',a:'DLavie mempertahankan minimum deposit Rp1.000. Saldo hanya boleh bertambah setelah pembayaran diverifikasi oleh backend/payment gateway; tampilan sukses di browser saja bukan bukti kredit saldo.',tags:['wallet','deposit','payment']},
 {q:'Apakah transaksi yang sama bisa terpotong dua kali?',a:'Backend Digital Market dirancang dengan idempotency, atomic order claim, dan ledger Wallet untuk mengurangi risiko double checkout, double debit, dan double refund. Jika terlihat transaksi ganda, simpan kedua reference ID dan laporkan melalui Bantuan.',tags:['idempotency','wallet','double']},
 {q:'Apa fungsi Cek status?',a:'Cek status digunakan untuk order reserved/pending yang belum mendapat hasil final. DLavie melakukan reconciliation secara terkontrol agar status supplier dapat diperbarui tanpa membuat transaksi baru secara sembarangan.',tags:['status','reconcile','pending']},
 {q:'Apakah Nomor Virtual dihapus?',a:'Tidak. Nomor Virtual tetap tersedia sebagai layanan tambahan di Digital Market. Aktivitas nomor/OTP tetap memiliki flow sendiri karena karakteristik sesi, waktu kedaluwarsa, dan supplier-nya berbeda dari produk pulsa atau tagihan.',tags:['nomor virtual','otp','nokos']},
 {q:'Bagaimana refund produk digital ditangani?',a:'Refund bergantung pada status transaksi dan bukti ledger. Transaksi gagal yang sudah mendebit Wallet harus dipulihkan secara idempotent. Transaksi yang sudah berhasil dikirim oleh supplier umumnya tidak dapat dibatalkan hanya karena salah memasukkan tujuan.',tags:['refund','ledger','failed']},
 {q:'Apa yang harus saya kirim saat meminta bantuan?',a:'Sertakan User ID, reference/order ID, kategori/produk, tujuan yang disamarkan bila sensitif, waktu kejadian, status terakhir, dan screenshot jika relevan. Jangan kirim password, token Wallet, credential supplier, Server Key, atau OTP sensitif.',tags:['support','security','reference']},
]

const faqEn:FAQ[]=[
 {q:'What is DLavie now?',a:'DLavie is a digital-products marketplace using one Wallet for mobile credit, data packages, PLN electricity, e-wallet top ups, vouchers & games, bill payments, and Virtual Number as an additional service.',tags:['basics','market']},
 {q:'Why do some categories show SYNC or 0 SKU?',a:'The category UI is ready but the supplier catalog has not been synchronized or supplier transactions are not enabled. DLavie does not invent live products or prices when the backend catalog is empty.',tags:['sync','supplier']},
 {q:'How does a prepaid purchase work?',a:'Fund the Wallet, choose a product, enter the destination carefully, and confirm. The backend verifies balance, creates a reference, sends the transaction to the supplier when enabled, and tracks the final status.',tags:['prepaid','wallet']},
 {q:'How do bill payments work?',a:'Postpaid products use an inquiry first. Review customer identity, period, details and total before paying. Wallet balance is charged at payment, not at inquiry.',tags:['postpaid','inquiry']},
 {q:'Where can I find an electricity token or serial number?',a:'Supplier output such as SN or token is shown on the receipt and order history when available. Keep the transaction reference for status checks and support.',tags:['token','receipt']},
 {q:'Is Virtual Number still available?',a:'Yes. Virtual Number remains an additional Digital Market service with its own OTP/session lifecycle.',tags:['virtual number','otp']},
 {q:'How are duplicate transactions prevented?',a:'The Digital Market backend uses request idempotency, atomic order claiming and Wallet ledger checks to reduce duplicate supplier calls, debits and refunds.',tags:['idempotency','wallet']},
 {q:'What should I include in a support request?',a:'Include User ID, transaction reference, product/category, incident time, last status and a screenshot when useful. Never send passwords, Wallet tokens, supplier credentials, Server Keys or sensitive OTPs.',tags:['support','security']},
]

const legalId:Record<LegalTab,Doc>={
 terms:{title:'Ketentuan Layanan',intro:'Aturan penggunaan akun, Wallet, Digital Market, produk prabayar/pascabayar, Nomor Virtual, pembayaran, supplier, dan transaksi DLavie.',sections:[
  {title:'1. Ruang lingkup layanan',paragraphs:['DLavie menyediakan antarmuka marketplace untuk membeli atau memproses produk digital dari supplier pihak ketiga. Produk dapat mencakup pulsa, paket data, listrik PLN, top up e-wallet, voucher/game, tagihan, dan Nomor Virtual.'],bullets:['Ketersediaan kategori, SKU, harga, stok, provider dan status dapat berubah mengikuti supplier.','Nomor Virtual adalah layanan tambahan dengan alur sesi/OTP tersendiri.','Label Testing, Sandbox, SYNC, transaksi OFF, atau Production harus dibaca sesuai status yang tampil.']},
  {title:'2. Akun dan Wallet',paragraphs:['Pengguna bertanggung jawab menjaga akses akun dan memastikan data tujuan transaksi benar. Wallet digunakan sebagai sumber pembayaran internal untuk layanan yang mendukungnya.'],bullets:['Saldo hanya boleh dikreditkan setelah pembayaran diverifikasi backend.','Debit dan refund dicatat melalui ledger/reference transaksi.','Pengguna wajib memeriksa saldo dan detail checkout sebelum konfirmasi.']},
  {title:'3. Produk prabayar',paragraphs:['Untuk produk prabayar, transaksi dapat diteruskan ke supplier setelah saldo dan request diverifikasi. Setelah supplier menyatakan sukses, produk umumnya dianggap telah diberikan.'],bullets:['Salah nomor tujuan, ID game, atau akun setelah transaksi sukses dapat membuat transaksi tidak dapat dibatalkan.','SN, token, atau message supplier merupakan bagian dari hasil transaksi bila tersedia.','Status pending bukan jaminan sukses maupun gagal sampai ada hasil final/reconciliation.']},
  {title:'4. Produk pascabayar dan inquiry',paragraphs:['Produk tagihan menggunakan proses inquiry untuk menampilkan detail pelanggan dan total sebelum pembayaran. Pengguna harus memeriksa hasil inquiry sebelum menyelesaikan pembayaran.'],bullets:['Inquiry bukan pembayaran dan tidak seharusnya mendebit Wallet.','Nominal dapat berasal dari supplier dan dapat mencakup komponen biaya yang ditampilkan sebelum bayar.','Pembayaran tagihan mengikuti reference dan aturan waktu supplier yang berlaku.']},
  {title:'5. Supplier dan pihak ketiga',paragraphs:['DLavie bergantung pada supplier produk digital, payment gateway, operator, biller, dan platform tujuan. Gangguan, maintenance, perubahan katalog, atau penolakan pihak ketiga dapat memengaruhi layanan.']},
  {title:'6. Harga, stok, dan perubahan katalog',paragraphs:['Harga jual dan ketersediaan yang berlaku adalah yang diverifikasi sistem pada saat transaksi. Harga preview atau data yang belum tersinkron tidak boleh dianggap penawaran final.']},
  {title:'7. Refund dan finalitas',paragraphs:['Refund diproses berdasarkan status transaksi, ledger Wallet, dan bukti dari supplier. Ketentuan rinci ada di tab Pembayaran & Refund. Transaksi sukses yang telah memenuhi produk ke tujuan yang dimasukkan pengguna umumnya final.']},
  {title:'8. Penggunaan yang dilarang',paragraphs:['DLavie tidak boleh digunakan untuk fraud, spam, account takeover, pencucian uang, eksploitasi promo, serangan sistem, penyalahgunaan massal, atau aktivitas yang melanggar hukum/kebijakan platform tujuan.']},
  {title:'9. Perubahan dan status dokumen',paragraphs:['Fitur Digital Market masih berkembang. Ketentuan dapat diperbarui ketika supplier, payment gateway, kategori, keamanan, atau regulasi berubah. Dokumen ini merupakan draft operasional pre-production dan perlu review hukum sebelum peluncuran publik penuh.']},
 ]},
 privacy:{title:'Kebijakan Privasi',intro:'Data yang dapat diproses untuk akun, Wallet, katalog, transaksi digital, inquiry tagihan, Nomor Virtual, keamanan dan dukungan.',sections:[
  {title:'1. Data akun dan perangkat',bullets:['Username, email, User ID, waktu akun dibuat, preferensi bahasa/tema dan metadata sesi yang diperlukan.','Sebagian state UI versi pengembangan dapat tersimpan di browser melalui localStorage/sessionStorage.']},
  {title:'2. Data Wallet dan pembayaran',bullets:['Wallet ID/token, saldo, deposit reference, nominal, metode pembayaran, status, timestamp dan data reconciliation yang relevan.','Secret payment gateway dan credential server tidak seharusnya ditanam di frontend.']},
  {title:'3. Data transaksi produk digital',bullets:['SKU, kategori, brand, nama produk, harga, reference ID, status, tujuan pelanggan, SN/token/message supplier jika tersedia.','Untuk tagihan: nama pelanggan, periode dan detail inquiry yang dikembalikan biller/supplier bila tersedia.','Untuk Nomor Virtual: service/provider, negara, nomor/sesi, status dan event OTP sesuai kebutuhan layanan.']},
  {title:'4. Tujuan pemrosesan',bullets:['Memenuhi pembelian, memverifikasi saldo, mencegah transaksi ganda, memperbarui status dan memberikan receipt.','Menangani refund, reconciliation, dispute, dukungan, keamanan dan pencegahan abuse.','Memenuhi kewajiban hukum yang berlaku.']},
  {title:'5. Pihak ketiga',paragraphs:['Data transaksi yang diperlukan dapat diteruskan ke supplier, biller, payment gateway, operator, atau provider terkait sejauh dibutuhkan untuk menjalankan layanan, keamanan, dukungan, atau kepatuhan.']},
  {title:'6. Retensi dan kontrol',paragraphs:['Data disimpan selama dibutuhkan untuk fulfillment, audit, pencegahan fraud, dispute dan kewajiban hukum. Jadwal retensi production harus diformalkan sebelum peluncuran publik penuh.']},
  {title:'7. Keamanan',paragraphs:['DLavie menggunakan pemisahan frontend/backend, token/reference, verifikasi server-side dan kontrol transaksi yang terus diperkuat. Tidak ada sistem yang dapat menjamin keamanan absolut.']},
 ]},
 refund:{title:'Pembayaran & Refund',intro:'Cara Wallet, pembayaran supplier, status gagal/pending, pengembalian dana, dan transaksi final ditangani.',sections:[
  {title:'1. Deposit Wallet',bullets:['Minimum deposit yang disiapkan adalah Rp1.000.','Saldo dikreditkan setelah backend memverifikasi pembayaran valid.','Deposit pending/expired/failed tidak boleh dianggap saldo tersedia.']},
  {title:'2. Debit transaksi',paragraphs:['Sebelum transaksi supplier, backend memverifikasi user, Wallet, SKU, harga dan konfigurasi transaksi. Sistem idempotency/ledger digunakan untuk mengurangi risiko debit atau supplier call ganda.']},
  {title:'3. Transaksi gagal',paragraphs:['Jika Wallet sudah didebit tetapi supplier memberi hasil gagal yang valid, sistem harus mengembalikan dana sesuai ledger secara idempotent. Nilai refund mengikuti debit transaksi yang sah dan aturan harga/biaya yang berlaku.']},
  {title:'4. Transaksi pending',paragraphs:['Pending belum final. DLavie dapat melakukan status check/reconciliation secara terkontrol. Pengguna sebaiknya tidak membuat pembelian pengganti berulang sebelum status transaksi awal jelas.']},
  {title:'5. Transaksi sukses',paragraphs:['Produk yang telah sukses dikirim ke tujuan yang dimasukkan pengguna umumnya final dan tidak dapat direfund karena kesalahan input pengguna. Periksa nomor, ID pelanggan, akun, atau game ID sebelum membayar.']},
  {title:'6. Tagihan pascabayar',paragraphs:['Inquiry harus diperiksa sebelum pembayaran. Setelah pembayaran tagihan sukses diterima biller/supplier, pembatalan bergantung pada kemampuan pihak ketiga dan tidak dijamin.']},
  {title:'7. Nomor Virtual',paragraphs:['Refund Nomor Virtual mengikuti lifecycle sesi, status provider, penerimaan OTP, kedaluwarsa dan kebijakan layanan tersebut. Aturannya dapat berbeda dari produk digital prabayar.']},
 ]},
 acceptable:{title:'Acceptable Use',intro:'Penggunaan DLavie harus sah, wajar, dan tidak merugikan pengguna lain, supplier, platform tujuan atau sistem pembayaran.',sections:[
  {title:'1. Dilarang untuk fraud dan penyalahgunaan',bullets:['Penipuan, impersonation, account takeover, social engineering atau transaksi tanpa otorisasi.','Spam, harassment, penyalahgunaan SMS/OTP, pembuatan akun massal untuk menghindari enforcement, atau eksploitasi promo.','Manipulasi pembayaran, chargeback abuse, penggunaan credential curian atau pencucian uang.']},
  {title:'2. Dilarang menyerang sistem',bullets:['Mencoba mengambil secret, token, credential supplier atau data pengguna lain.','Automasi berlebihan yang mengganggu layanan, scraping yang melanggar kebijakan, bypass rate limit, atau eksploitasi bug.']},
  {title:'3. Kepatuhan platform tujuan',paragraphs:['Pengguna tetap bertanggung jawab mematuhi aturan operator, biller, game, e-wallet, aplikasi tujuan, dan hukum yang berlaku. Tersedianya sebuah produk di katalog bukan izin untuk melanggar ketentuan pihak ketiga.']},
  {title:'4. Penegakan',paragraphs:['DLavie dapat membatasi transaksi, menahan flow berisiko, meminta verifikasi tambahan, atau menangguhkan akses bila terdapat indikasi abuse, risiko keamanan, fraud, atau kewajiban hukum.']},
 ]},
 disclosure:{title:'Service Disclosure',intro:'Batasan penting Digital Market, supplier, status transaksi, data katalog, dan layanan Nomor Virtual.',sections:[
  {title:'1. Supplier-dependent',paragraphs:['Produk digital DLavie bergantung pada supplier pihak ketiga. Harga, stok, SKU, brand, maintenance, kecepatan proses dan hasil transaksi dapat berubah di luar kontrol langsung DLavie.']},
  {title:'2. Katalog dan status environment',paragraphs:['Kartu kategori dapat tersedia sebelum katalog supplier tersinkron. Label SYNC/0 SKU menunjukkan belum ada produk supplier aktif pada kategori tersebut. Testing/Sandbox bukan transaksi uang production.']},
  {title:'3. Status transaksi',paragraphs:['Pending berarti hasil belum final. Status final seharusnya diperoleh dari response supplier, webhook, atau reconciliation yang tervalidasi. Callback browser saja tidak menjadi sumber kebenaran untuk saldo atau fulfillment.']},
  {title:'4. Harga dan fulfillment',paragraphs:['Harga yang relevan adalah harga yang diverifikasi server saat transaksi. SN, token atau hasil digital hanya ditampilkan jika supplier mengembalikannya. Waktu proses dapat berbeda antar produk.']},
  {title:'5. Nomor Virtual',paragraphs:['Nomor Virtual merupakan layanan tambahan dengan risiko khusus: nomor sementara, waktu sesi, ketersediaan negara/provider, filtering SMS, dan tidak adanya jaminan OTP dari platform tujuan.']},
  {title:'6. Pre-production',paragraphs:['DLavie masih dalam tahap pengembangan menuju production. Fitur, supplier, payment channel dan dokumen operasional dapat berubah. Jangan menganggap label UI sebagai jaminan layanan production jika konfigurasi backend belum diaktifkan.']},
 ]},
}

const legalEn:Record<LegalTab,Doc>={
 terms:{title:'Terms of Service',intro:'Rules for accounts, Wallet, Digital Market, prepaid/postpaid products, Virtual Number, payments and supplier transactions.',sections:[
  {title:'1. Scope',paragraphs:['DLavie provides a marketplace interface for digital products fulfilled by third-party suppliers, including mobile credit, data, PLN electricity, e-wallet top ups, vouchers/games, bill payments and Virtual Number.'],bullets:['Catalog, SKU, price, stock and provider availability may change.','Virtual Number is an additional service with a separate OTP/session lifecycle.','Testing, Sandbox, SYNC and Production labels must be read as displayed.']},
  {title:'2. Wallet and transactions',paragraphs:['Wallet balance is used for supported purchases. Credits, debits and refunds must be validated and traceable through server-side references/ledger records.']},
  {title:'3. Prepaid and postpaid products',paragraphs:['Prepaid purchases can be sent to a supplier after validation. Postpaid products use inquiry before payment so customers can review identity, period and total. Successful fulfillment is generally final.']},
  {title:'4. Third parties',paragraphs:['DLavie depends on suppliers, billers, payment gateways, carriers and destination services. Their outages, catalog changes or rejections can affect service availability.']},
  {title:'5. Prohibited use and changes',paragraphs:['Fraud, abuse, account takeover, spam, payment manipulation and attacks on DLavie or third parties are prohibited. These operational terms may change as the product moves toward Production.']},
 ]},
 privacy:{title:'Privacy Policy',intro:'Data used for accounts, Wallet, digital orders, bill inquiry, Virtual Number, security and support.',sections:[
  {title:'1. Data categories',bullets:['Account identifiers and settings.','Wallet, deposit and transaction metadata.','Product SKU/category/brand, destination, status and supplier output.','Bill inquiry customer/period/detail data when returned by a biller.','Virtual Number session/OTP metadata when needed for that service.']},
  {title:'2. Purposes and third parties',paragraphs:['Data is processed to fulfill orders, verify Wallet balance, prevent duplicates/fraud, reconcile status, handle refunds and provide support. Necessary transaction data may be shared with suppliers, billers and payment providers.']},
  {title:'3. Retention and security',paragraphs:['Retention is based on fulfillment, audit, fraud prevention, disputes and legal requirements. DLavie separates browser UI from server-side secrets and continues to harden transaction controls.']},
 ]},
 refund:{title:'Payment & Refund',intro:'Wallet deposits, supplier debits, pending/failed orders, refunds and successful fulfillment.',sections:[
  {title:'1. Wallet',bullets:['The current minimum deposit is Rp1,000.','Balance is credited only after server verification.','Pending or failed deposits are not available balance.']},
  {title:'2. Failed and pending orders',paragraphs:['A valid supplier failure after a Wallet debit should trigger an idempotent refund. Pending orders are not final and may require controlled status reconciliation.']},
  {title:'3. Successful orders',paragraphs:['Successfully fulfilled digital products are generally final, especially when an incorrect destination was entered by the user. Postpaid inquiry must be reviewed before payment. Virtual Number refunds follow its separate session lifecycle.']},
 ]},
 acceptable:{title:'Acceptable Use',intro:'DLavie must be used lawfully and without harming users, suppliers, payment systems or destination platforms.',sections:[
  {title:'1. Prohibited activity',bullets:['Fraud, impersonation, account takeover or unauthorized transactions.','Spam, abusive OTP use, mass-account abuse or enforcement bypass.','Payment manipulation, stolen credentials, chargeback abuse or money laundering.','Attempts to steal secrets, bypass controls or attack DLavie/supplier systems.']},
  {title:'2. Enforcement',paragraphs:['DLavie may restrict transactions, request additional verification or suspend access where abuse, fraud, security risk or legal obligations are identified.']},
 ]},
 disclosure:{title:'Service Disclosure',intro:'Important limits of Digital Market, suppliers, transaction status, catalog data and Virtual Number.',sections:[
  {title:'1. Supplier dependency',paragraphs:['Price, stock, SKU availability, maintenance and processing time depend on third-party suppliers.']},
  {title:'2. Environment and status',paragraphs:['SYNC/0 SKU means supplier catalog data is not yet active for that category. Testing/Sandbox is not Production. Pending status is not final; validated supplier responses, webhooks or reconciliation determine final status.']},
  {title:'3. Virtual Number and pre-production',paragraphs:['Virtual Number has separate risks including temporary numbers and non-guaranteed OTP delivery. DLavie remains in active development toward Production, so features and operational documents may change.']},
 ]},
}

function LegalDocument({tab,en}:{tab:LegalTab;en:boolean}){
 const doc=(en?legalEn:legalId)[tab]
 return <article className="legal-document"><header><span>DLAVIE · DIGITAL MARKET</span><h2>{doc.title}</h2><p>{doc.intro}</p><div><b>{en?'Updated':'Diperbarui'} · {en?UPDATED_EN:UPDATED_ID}</b><em>PRE-PRODUCTION</em></div></header>{doc.sections.map(section=><section key={section.title}><h3>{section.title}</h3>{section.paragraphs?.map((p,i)=><p key={i}>{p}</p>)}{section.bullets&&<ul>{section.bullets.map((b,i)=><li key={i}>{b}</li>)}</ul>}</section>)}<aside>{en?'Operational product copy for transparency. Obtain qualified legal review before a full Production launch.':'Copy operasional untuk transparansi produk. Lakukan review hukum yang kompeten sebelum peluncuran Production penuh.'}</aside></article>
}

export default function DigitalPolicyCenterV2(){
 const [en,setEn]=useState(english)
 const [query,setQuery]=useState('')
 const [open,setOpen]=useState<number|null>(0)
 const [tab,setTab]=useState<LegalTab>('terms')
 const [revision,setRevision]=useState(0)
 useEffect(()=>{const sync=()=>{setEn(english());setRevision(x=>x+1)};const route=()=>{const raw=location.hash.split('?')[1]||'';const next=new URLSearchParams(raw).get('tab') as LegalTab|null;if(next&&['terms','privacy','refund','acceptable','disclosure'].includes(next))setTab(next);setOpen(0)};sync();route();window.addEventListener('storage',sync);window.addEventListener('dlavie:state-changed',sync);window.addEventListener('hashchange',route);return()=>{window.removeEventListener('storage',sync);window.removeEventListener('dlavie:state-changed',sync);window.removeEventListener('hashchange',route)}},[])
 const faqs=en?faqEn:faqId
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?faqs.filter(x=>`${x.q} ${x.a} ${x.tags.join(' ')}`.toLowerCase().includes(q)):faqs},[faqs,query])
 const p=useMemo(()=>profile(),[revision])
 const tabs:Array<{id:LegalTab;idLabel:string;enLabel:string}>=[{id:'terms',idLabel:'Ketentuan Layanan',enLabel:'Terms of Service'},{id:'privacy',idLabel:'Kebijakan Privasi',enLabel:'Privacy Policy'},{id:'refund',idLabel:'Pembayaran & Refund',enLabel:'Payment & Refund'},{id:'acceptable',idLabel:'Acceptable Use',enLabel:'Acceptable Use'},{id:'disclosure',idLabel:'Service Disclosure',enLabel:'Service Disclosure'}]
 return <>
  <section className="help-center-page market-info-page dlv-content-v2" aria-label={en?'DLavie Digital Market Help':'Bantuan Digital Market DLavie'}><div className="market-info-shell">
   <header className="info-hero"><span>DLAVIE · DIGITAL MARKET SUPPORT</span><h1>{en?'Help for every digital order.':'Bantuan untuk setiap transaksi digital.'}</h1><p>{en?'Wallet, supplier catalog, prepaid products, bill inquiry, status, refunds and Virtual Number in one knowledge base.':'Wallet, katalog supplier, produk prabayar, inquiry tagihan, status, refund, dan Nomor Virtual dalam satu pusat bantuan.'}</p><div className="info-hero-meta"><b>{p?.username||p?.id||(en?'Guest user':'Pengguna tamu')}</b><i/><span>{en?'Digital Market knowledge base':'Knowledge base Digital Market'}</span></div></header>
   <label className="faq-search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={en?'Search Wallet, product, bill, status, refund…':'Cari Wallet, produk, tagihan, status, refund…'}/><kbd>{filtered.length}</kbd></label>
   <div className="support-quick-grid"><article><span>01</span><strong>{en?'Keep the transaction reference':'Simpan reference transaksi'}</strong><p>{en?'Reference IDs connect Wallet, supplier status, receipts and support.':'Reference ID menghubungkan Wallet, status supplier, receipt, dan bantuan.'}</p></article><article><span>02</span><strong>{en?'Verify the destination':'Periksa tujuan sebelum bayar'}</strong><p>{en?'Phone number, customer ID and game account errors can make successful orders final.':'Kesalahan nomor, ID pelanggan, atau akun game dapat membuat transaksi sukses bersifat final.'}</p></article><article><span>03</span><strong>{en?'Read supplier status':'Baca status supplier'}</strong><p>{en?'SYNC, Testing, Pending and Production each describe a different system state.':'SYNC, Testing, Pending, dan Production memiliki arti status yang berbeda.'}</p></article></div>
   <div className="faq-layout"><aside className="support-reference"><span>{en?'SUPPORT CHECKLIST':'CHECKLIST BANTUAN'}</span><h2>{en?'Prepare traceable information':'Siapkan informasi yang bisa dilacak'}</h2><p>{en?'Give support enough context without exposing credentials.':'Berikan konteks yang cukup tanpa membocorkan credential.'}</p><dl><div><dt>User ID</dt><dd>{p?.id||'—'}</dd></div><div><dt>Reference ID</dt><dd>{en?'From Activity / receipt':'Dari Aktivitas / receipt'}</dd></div><div><dt>{en?'Product':'Produk'}</dt><dd>{en?'Category · brand · SKU if visible':'Kategori · brand · SKU jika terlihat'}</dd></div><div><dt>{en?'Never send':'Jangan kirim'}</dt><dd>{en?'Password, Wallet token, supplier secret, OTP':'Password, token Wallet, secret supplier, OTP'}</dd></div></dl></aside><div className="faq-list">{filtered.length?filtered.map((item,index)=><article className={open===index?'open':''} key={item.q}><button type="button" onClick={()=>setOpen(open===index?null:index)} aria-expanded={open===index}><span><small>{String(index+1).padStart(2,'0')}</small><strong>{item.q}</strong></span><b>{open===index?'−':'+'}</b></button>{open===index&&<p>{item.a}</p>}</article>):<div className="faq-empty">{en?'No matching answer yet.':'Belum ada jawaban yang cocok.'}</div>}</div></div>
   <section className="support-policy-callout"><div><span>{en?'TRANSACTION RULES':'ATURAN TRANSAKSI'}</span><h2>{en?'Read payment, refund, privacy and supplier disclosures before Production use.':'Baca aturan pembayaran, refund, privasi, dan disclosure supplier sebelum penggunaan Production.'}</h2></div><button onClick={()=>{location.hash='/legal'}}>{en?'Open Legal Center':'Buka Legal Center'} <b>→</b></button></section>
  </div></section>
  <section className="legal-center-page market-info-page dlv-content-v2" aria-label={en?'DLavie Digital Market Legal Center':'Legal Center Digital Market DLavie'}><div className="market-info-shell legal-shell"><header className="info-hero legal-hero"><span>DLAVIE · DIGITAL MARKET LEGAL</span><h1>{en?'Rules built around the real transaction flow.':'Aturan yang mengikuti alur transaksi sebenarnya.'}</h1><p>{en?'Wallet, suppliers, prepaid products, bill inquiry, refunds, privacy and Virtual Number are documented in one place.':'Wallet, supplier, produk prabayar, inquiry tagihan, refund, privasi, dan Nomor Virtual didokumentasikan dalam satu tempat.'}</p><div className="info-hero-meta"><b>{en?'Updated':'Diperbarui'} · {en?UPDATED_EN:UPDATED_ID}</b><i/><span>PRE-PRODUCTION</span></div></header><div className="legal-layout"><nav className="legal-tabs" aria-label="Legal documents">{tabs.map(x=><button type="button" key={x.id} className={tab===x.id?'active':''} onClick={()=>{setTab(x.id);history.replaceState(null,'',`${location.pathname}${location.search}#/legal?tab=${x.id}`)}}><span>{en?x.enLabel:x.idLabel}</span><b>→</b></button>)}</nav><LegalDocument tab={tab} en={en}/></div></div></section>
 </>
}
