import { useCallback, useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import { digitalAuth,digitalCall,money,type DigitalOrder } from './digital-market-api'

type Page='market'|'guide'|'security'|'activity'|null
type Item={label:string;value:string;tone?:'good'|'warn'|'muted'}
type Context={eyebrow:string;title:string;subtitle:string;rail:Item[];groups:Array<{title:string;items:Item[]}>}
const STATE_EVENT='dlavie:state-changed'
function route():Page{const r=location.hash.replace(/^#\/?/,'').split('?')[0].toLowerCase();if(r==='market')return'market';if(r==='guide'||r==='cara-kerja')return'guide';if(r==='security'||r==='keamanan')return'security';if(r==='activity'||r==='aktivitas')return'activity';return null}
function en(){return localStorage.getItem('dlavie-language')==='en'}
function virtualOrders(){try{return JSON.parse(localStorage.getItem('dlavie-orders-v1')||'[]') as Array<{status?:string}>}catch{return[]}}

export default function DigitalRouteContextV2(){
 const [page,setPage]=useState<Page>(route)
 const [target,setTarget]=useState<HTMLElement|null>(null)
 const [expanded,setExpanded]=useState(false)
 const [integration,setIntegration]=useState<any>(null)
 const [summary,setSummary]=useState<any[]>([])
 const [orders,setOrders]=useState<DigitalOrder[]>([])
 const [balance,setBalance]=useState(()=>Number(localStorage.getItem('dlavie-balance')||0))
 const [english,setEnglish]=useState(en)
 const load=useCallback(async()=>{if(!route())return;try{const s=await digitalCall('summary');setIntegration(s.integration||null);setSummary(s.summary||[])}catch{}const a=digitalAuth();if(a.wallet_token&&a.user_id){try{const h=await digitalCall('history',a);setOrders(h.orders||[]);if(typeof h.balance==='number')setBalance(h.balance)}catch{}}},[])
 useEffect(()=>{let timer=0;const resolve=()=>{clearTimeout(timer);const p=route();setPage(p);setExpanded(false);setEnglish(en());if(!p){setTarget(null);return}const selector=p==='market'?'.dlv-digital-hero':p==='guide'?'.experience-card':p==='security'?'.security':'.order-center-head';const el=document.querySelector<HTMLElement>(selector);if(el)setTarget(el);else timer=window.setTimeout(resolve,100);void load()};resolve();window.addEventListener('hashchange',resolve);return()=>{clearTimeout(timer);window.removeEventListener('hashchange',resolve)}},[load])
 useEffect(()=>{const sync=()=>{setBalance(Number(localStorage.getItem('dlavie-balance')||0));setEnglish(en());void load()};window.addEventListener(STATE_EVENT,sync);window.addEventListener('storage',sync);window.addEventListener('focus',sync);return()=>{window.removeEventListener(STATE_EVENT,sync);window.removeEventListener('storage',sync);window.removeEventListener('focus',sync)}},[load])
 const context=useMemo<Context|null>(()=>{if(!page)return null;const sku=Number(integration?.catalog_count||0);const env=integration?.enabled?(integration.environment==='production'?'Production':'Testing'):(english?'Not enabled':'Belum aktif');const prepaid=summary.filter(x=>x.product_kind==='prepaid').reduce((n,x)=>n+Number(x.product_count||0),0);const postpaid=summary.filter(x=>x.product_kind==='postpaid').reduce((n,x)=>n+Number(x.product_count||0),0);const pending=orders.filter(x=>['created','reserved','pending','inquired'].includes(x.status)).length;const vActive=virtualOrders().filter(x=>x.status==='waiting'||x.status==='received').length
  if(page==='market')return{eyebrow:'DIGITAL MARKET CONTEXT',title:english?'Live marketplace state':'Status marketplace saat ini',subtitle:english?'Wallet, supplier catalog, environment and supported transaction modes.':'Wallet, katalog supplier, environment, dan mode transaksi yang didukung.',rail:[{label:'Wallet',value:money.format(balance),tone:balance>0?'good':'muted'},{label:english?'Supplier catalog':'Katalog supplier',value:`${sku} SKU`,tone:sku?'good':'warn'},{label:'Environment',value:env,tone:integration?.environment==='production'?'good':'warn'},{label:'Postpaid',value:integration?.postpaid_enabled?(english?'Enabled':'Aktif'):(english?'Disabled':'Belum aktif'),tone:integration?.postpaid_enabled?'good':'muted'}],groups:[{title:english?'Product coverage':'Cakupan produk',items:[{label:english?'Prepaid products':'Produk prabayar',value:String(prepaid)},{label:english?'Postpaid services':'Layanan pascabayar',value:String(postpaid)},{label:'Virtual Number',value:english?'Additional service':'Layanan tambahan'}]},{title:english?'Transaction truth':'Sumber kebenaran transaksi',items:[{label:english?'Price & SKU':'Harga & SKU',value:english?'Backend catalog':'Katalog backend'},{label:english?'Final status':'Status final',value:english?'Supplier response / webhook / reconciliation':'Response supplier / webhook / reconciliation'},{label:english?'Wallet changes':'Perubahan Wallet',value:english?'Server ledger':'Ledger server'}]}]}
  if(page==='guide')return{eyebrow:'DIGITAL MARKET FLOW',title:english?'How DLavie transactions work':'Cara transaksi DLavie bekerja',subtitle:english?'Different products use the flow that matches their fulfillment model.':'Setiap jenis produk memakai flow yang sesuai dengan cara fulfillment-nya.',rail:[{label:english?'Prepaid':'Prabayar',value:english?'Checkout → supplier':'Checkout → supplier'},{label:'Postpaid',value:english?'Inquiry → pay':'Inquiry → bayar'},{label:'Virtual Number',value:english?'Session → OTP':'Sesi → OTP'},{label:'Wallet',value:english?'Server verified':'Terverifikasi server',tone:'good'}],groups:[{title:english?'Prepaid flow':'Flow prabayar',items:[{label:'01',value:english?'Choose category & SKU':'Pilih kategori & SKU'},{label:'02',value:english?'Enter destination':'Masukkan tujuan'},{label:'03',value:english?'Reserve/debit Wallet':'Reserve/debit Wallet'},{label:'04',value:english?'Supplier status + receipt':'Status supplier + receipt'}]},{title:english?'Postpaid flow':'Flow pascabayar',items:[{label:'01',value:english?'Select biller/service':'Pilih biller/layanan'},{label:'02',value:english?'Inquiry customer & total':'Inquiry pelanggan & total'},{label:'03',value:english?'Review details':'Periksa detail'},{label:'04',value:english?'Pay with Wallet':'Bayar dengan Wallet'}]},{title:'Virtual Number',items:[{label:english?'Position':'Posisi',value:english?'Additional Digital Market service':'Layanan tambahan Digital Market'},{label:english?'Lifecycle':'Lifecycle',value:english?'Allocate → wait SMS/OTP → expire/finish':'Alokasi → tunggu SMS/OTP → selesai/kedaluwarsa'}]}]}
  if(page==='security')return{eyebrow:'DIGITAL MARKET SECURITY',title:english?'Transaction boundaries & controls':'Batas dan kontrol transaksi',subtitle:english?'Sensitive supplier and payment operations stay behind the browser UI.':'Operasi supplier dan pembayaran yang sensitif berada di belakang UI browser.',rail:[{label:english?'Supplier credentials':'Credential supplier',value:english?'Backend only':'Backend only',tone:'good'},{label:english?'Wallet ledger':'Ledger Wallet',value:english?'Server-side':'Server-side',tone:'good'},{label:'Idempotency',value:english?'Active design':'Dirancang aktif',tone:'good'},{label:english?'Account auth':'Auth akun',value:english?'Still pre-production':'Masih pre-production',tone:'warn'}],groups:[{title:english?'Transaction controls':'Kontrol transaksi',items:[{label:'Double checkout',value:english?'Atomic claim / active intent':'Atomic claim / active intent',tone:'good'},{label:'Debit / refund',value:english?'Ledger idempotency':'Idempotency ledger',tone:'good'},{label:english?'Pending orders':'Order pending',value:'Reconciliation',tone:'good'}]},{title:english?'Supplier controls':'Kontrol supplier',items:[{label:'Webhook',value:english?'Signed callback handling':'Penanganan callback bertanda tangan',tone:'good'},{label:english?'Final state':'Status final',value:english?'Protected from late rollback':'Dilindungi dari rollback callback terlambat',tone:'good'},{label:english?'Production switch':'Aktivasi Production',value:english?'Admin readiness checks':'Pemeriksaan readiness admin',tone:'good'}]},{title:english?'Before public Production':'Sebelum Production publik',items:[{label:english?'Account authentication':'Autentikasi akun',value:english?'Move fully server-side':'Pindahkan penuh ke server',tone:'warn'},{label:english?'Supplier catalog':'Katalog supplier',value:sku?`${sku} SKU`:(english?'Synchronize catalog':'Sinkronkan katalog'),tone:sku?'good':'warn'}]}]}
  return{eyebrow:'ACTIVITY CONTEXT',title:english?'Digital transaction timeline':'Timeline transaksi digital',subtitle:english?'Digital orders first, with Wallet movements and Virtual Number sessions alongside them.':'Order digital menjadi fokus utama, bersama pergerakan Wallet dan sesi Nomor Virtual.',rail:[{label:english?'Digital orders':'Order digital',value:String(orders.length)},{label:english?'Needs attention':'Perlu perhatian',value:String(pending),tone:pending?'warn':'good'},{label:'Virtual Number',value:String(vActive)},{label:'Wallet',value:money.format(balance)}],groups:[{title:english?'Digital orders':'Order digital',items:[{label:english?'Total recorded':'Total tercatat',value:String(orders.length)},{label:english?'Pending / reserved':'Pending / reserved',value:String(pending)},{label:english?'Latest reference':'Reference terbaru',value:orders[0]?.ref_id||'—'}]},{title:english?'Services in this timeline':'Layanan dalam timeline',items:[{label:english?'Prepaid':'Prabayar',value:english?'Credit, data, PLN, wallet, vouchers':'Pulsa, data, PLN, wallet, voucher'},{label:'Postpaid',value:english?'Bill inquiry & payment':'Inquiry & pembayaran tagihan'},{label:'Virtual Number',value:english?'Separate OTP sessions':'Sesi OTP terpisah'}]}]}
 },[page,integration,summary,orders,balance,english])
 if(!target||!context)return null
 return createPortal(<section className={`site-context dlv-digital-context-v2 ${expanded?'is-expanded':''}`} aria-label={context.title}><div className="site-context-head"><div><span>{context.eyebrow}</span><strong>{context.title}</strong><small>{context.subtitle}</small></div><button type="button" onClick={()=>setExpanded(x=>!x)} aria-expanded={expanded}><span>{expanded?(english?'Close details':'Tutup detail'):(english?'View details':'Lihat detail')}</span><b>{expanded?'−':'+'}</b></button></div><div className="site-context-rail">{context.rail.map(x=><div key={`${x.label}-${x.value}`} data-tone={x.tone||'muted'}><small>{x.label}</small><strong>{x.value}</strong></div>)}</div>{expanded&&<div className="site-context-detail">{context.groups.map(g=><section key={g.title}><h4>{g.title}</h4><div>{g.items.map(x=><p key={`${g.title}-${x.label}`} data-tone={x.tone||'muted'}><span>{x.label}</span><b>{x.value}</b></p>)}</div></section>)}</div>}</section>,target)
}
