export type DigitalSummary={category:string;product_kind:string;product_count:number;min_price:number;max_price:number;brands:string[]}
export type DigitalProduct={sku:string;product_kind:string;product_name:string;category:string;brand:string;product_type?:string|null;sell_price:number;base_price?:number;admin_fee?:number|null;commission?:number|null;unlimited_stock:boolean;stock:number;multi:boolean;description?:string|null;requires_extended_input?:boolean;synced_at:string}
export type DigitalOrder={ref_id:string;product_kind:string;sku:string;product_name:string;category:string;brand:string;product_type?:string|null;customer_no:string;customer_name?:string|null;period?:string|null;sell_price:number;status:string;supplier_status?:string|null;rc?:string|null;message?:string|null;serial_number?:string|null;environment:string;created_at:string;updated_at:string;inquired_at?:string|null;inquiry_valid_until?:string|null;inquiry_admin?:number|null;inquiry_price?:number|null;inquiry_selling_price?:number|null;inquiry_detail?:Record<string,unknown>|null;completed_at?:string|null;refunded_at?:string|null;user_data_confirmed?:boolean;policy_accepted?:boolean;policy_version?:string|null;purchase_confirmed_at?:string|null;payment_confirmed_at?:string|null}
export type DigitalIntegration={provider?:string;environment:string;enabled:boolean;production_enabled?:boolean;postpaid_enabled?:boolean;catalog_count:number;last_sync?:string|null;status?:string|null}
export type DigitalExtendedKind='pbb'|'emoney'|'samsat'|null
const API='https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-digital-market-h2h-v22'
const TOKEN='dlavie-wallet-token-v1',PROFILE='dlavie-account-profile-v1',PAY_CONFIRM='dlavie-postpaid-pay-confirm-v22'
const POLICY_VERSION='2026-08-20-digital-v1'
export const money=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0})
export const when=(v?:string|null)=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(v)):'—'
export function digitalAuth(){let user_id='';try{user_id=JSON.parse(localStorage.getItem(PROFILE)||'null')?.id||''}catch{}return{wallet_token:localStorage.getItem(TOKEN)||'',user_id}}
export function digitalRoute(){const raw=location.hash.replace(/^#\/?/,'');const [name,q='']=raw.split('?');return{name:name.toLowerCase(),params:new URLSearchParams(q)}}
export function isDigitalMarket(){const r=digitalRoute();return r.name==='market'&&r.params.get('mode')!=='nokos'}
const errorMap:Record<string,string>={auth_required:'Buka Wallet sekali agar wallet akun aktif.',credentials_required:'Credential H2H.id belum lengkap.',insufficient_balance:'Saldo wallet tidak cukup.',sandbox_insufficient_balance:'Saldo Sandbox DLavie tidak cukup. Saldo tes terpisah dari Wallet asli.',product_unavailable:'Produk sedang tidak tersedia.',digital_market_disabled:'Digital Market belum siap digunakan.',integration_not_ready:'Koneksi H2H.id sedang disiapkan.',postpaid_disabled:'Pembayaran tagihan belum diaktifkan admin.',inquiry_required:'Cek tagihan terlebih dahulu sebelum membayar.',inquiry_failed:'Tagihan tidak dapat ditemukan atau inquiry gagal.',inquiry_expired:'Tagihan harus dicek ulang karena inquiry sudah kedaluwarsa.',postpaid_not_payable:'Tagihan ini sudah diproses atau tidak lagi dapat dibayar.',extended_input_required:'Produk ini memerlukan data tambahan khusus.',extended_input_not_applicable:'Format tambahan tidak cocok dengan produk ini.',invalid_amount:'Nominal tidak valid.',invalid_year:'Tahun pajak tidak valid.',invalid_samsat_target:'Data SAMSAT belum lengkap.',status_cooldown:'Tunggu sekitar 1 menit sebelum cek ulang.',supplier_rejected:'H2H.id menolak transaksi. Saldo DLavie dikembalikan bila sudah sempat direservasi.',invalid_inquiry_amount:'Nominal inquiry dari supplier tidak valid.',status_not_checkable:'Status order ini belum dapat dicek ke supplier.',purchase_confirmation_required:'Centang pemeriksaan data dan kebijakan transaksi sebelum melanjutkan.',payment_confirmation_required:'Konfirmasi kembali detail tagihan dan total sebelum membayar.',market_guard_error:'Pengaman transaksi belum dapat memproses permintaan. Coba lagi.'}
async function request(url:string,action:string,extra:Record<string,string>={}){const guarded=action==='purchase'||action==='inquiry_postpaid';const paying=action==='pay_postpaid';const payConfirmed=paying&&sessionStorage.getItem(PAY_CONFIRM)==='true';if(paying)sessionStorage.removeItem(PAY_CONFIRM);const body=new URLSearchParams({action,...extra,...(guarded?{confirm_data:'true',accept_policy:'true',policy_version:POLICY_VERSION}:{}),...(paying?{payment_confirmed:payConfirmed?'true':'false',policy_version:POLICY_VERSION}:{})});const r=await fetch(url,{method:'POST',body});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(errorMap[d.error]||d.message||'Permintaan belum dapat diproses.');return d}
export function digitalCall(action:string,extra:Record<string,string>={}){return request(API,action,extra)}
export function digitalExtendedCall(extra:Record<string,string>={}){return request(API,'inquiry_postpaid',extra)}
export function digitalExtendedKind(product?:Pick<DigitalProduct,'category'|'brand'|'product_name'|'sku'|'requires_extended_input'>|null):DigitalExtendedKind{if(!product?.requires_extended_input)return null;const x=`${product.category} ${product.brand} ${product.product_name} ${product.sku}`.toLowerCase();if(x.includes('samsat')||x.includes('pajak kendaraan'))return'samsat';if(x.includes('e-money')||x.includes('emoney'))return'emoney';if(x.includes('pbb'))return'pbb';return null}
export function digitalTargetLabel(category:string,brand=''){const x=`${category} ${brand}`.toLowerCase();if(x.includes('pln'))return'No. meter / ID pelanggan';if(x.includes('bpjs'))return'No. peserta / ID pelanggan';if(x.includes('pdam'))return'No. pelanggan PDAM';if(x.includes('internet')||x.includes('tv'))return'ID pelanggan';if(x.includes('game'))return'User ID / tujuan';if(x.includes('wallet')||x.includes('money'))return'Nomor / ID e-wallet';if(x.includes('data')||x.includes('pulsa'))return'Nomor HP tujuan';return'Nomor / ID pelanggan'}
export function digitalStatus(v:string){if(v==='success')return'Sukses';if(v==='inquired')return'Tagihan ditemukan';if(v==='refunded')return'Gagal · saldo kembali';if(v==='failed')return'Gagal';if(v==='reserved')return'Menunggu supplier';if(v==='pending'||v==='created')return'Diproses';return v}
