export type DigitalSummary={category:string;product_kind:string;product_count:number;min_price:number;max_price:number;brands:string[]}
export type DigitalProduct={sku:string;product_kind:string;product_name:string;category:string;brand:string;product_type?:string|null;sell_price:number;unlimited_stock:boolean;stock:number;multi:boolean;description?:string|null;synced_at:string}
export type DigitalOrder={ref_id:string;product_kind:string;sku:string;product_name:string;category:string;brand:string;product_type?:string|null;customer_no:string;sell_price:number;status:string;supplier_status?:string|null;rc?:string|null;message?:string|null;serial_number?:string|null;environment:string;created_at:string;updated_at:string;completed_at?:string|null;refunded_at?:string|null}
export type DigitalIntegration={environment:string;enabled:boolean;catalog_count:number;last_sync?:string|null;status?:string|null}
const API='https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-digital-market'
const TOKEN='dlavie-wallet-token-v1',PROFILE='dlavie-account-profile-v1'
export const money=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0})
export const when=(v?:string|null)=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(v)):'—'
export function digitalAuth(){let user_id='';try{user_id=JSON.parse(localStorage.getItem(PROFILE)||'null')?.id||''}catch{}return{wallet_token:localStorage.getItem(TOKEN)||'',user_id}}
export function digitalRoute(){const raw=location.hash.replace(/^#\/?/,'');const [name,q='']=raw.split('?');return{name:name.toLowerCase(),params:new URLSearchParams(q)}}
export function isDigitalMarket(){const r=digitalRoute();return r.name==='market'&&r.params.get('mode')!=='nokos'}
export async function digitalCall(action:string,extra:Record<string,string>={}){const body=new URLSearchParams({action,...extra});const r=await fetch(API,{method:'POST',body});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){const map:Record<string,string>={auth_required:'Buka Wallet sekali agar wallet akun aktif.',insufficient_balance:'Saldo wallet tidak cukup.',product_unavailable:'Produk sedang tidak tersedia.',digital_market_disabled:'Transaksi produk digital belum diaktifkan.',integration_not_ready:'Koneksi supplier sedang disiapkan.',postpaid_not_ready:'Pascabayar belum tersedia pada flow ini.',status_cooldown:'Tunggu sekitar 1 menit sebelum cek ulang.'};throw new Error(map[d.error]||d.message||'Permintaan belum dapat diproses.')}return d}
export function digitalTargetLabel(category:string){const x=category.toLowerCase();if(x.includes('pln'))return'No. meter / ID pelanggan';if(x.includes('game'))return'User ID / tujuan';if(x.includes('wallet')||x.includes('money'))return'Nomor e-wallet';if(x.includes('data')||x.includes('pulsa'))return'Nomor HP tujuan';return'Nomor / ID tujuan'}
export function digitalStatus(v:string){if(v==='success')return'Sukses';if(v==='refunded')return'Gagal · saldo kembali';if(v==='failed')return'Gagal';if(v==='pending'||v==='reserved')return'Diproses';return v}
