import { FormEvent, useEffect, useState } from 'react'
const API='https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-digiflazz-admin',TOKEN='dlavie-admin-support-session-v1'
type Settings={environment:string;markup_mode:string;markup_value:number;minimum_markup:number;live_enabled:boolean;gateway_url?:string|null;catalog_count:number;postpaid_enabled:boolean;last_catalog_sync_at?:string|null;last_catalog_sync_status?:string|null;last_catalog_sync_message?:string|null}
type Status={settings:Settings;secrets:{username:boolean;api_key:boolean;gateway_secret:boolean;webhook_secret:boolean}}
async function call(action:string,extra:Record<string,string>={}){const token=sessionStorage.getItem(TOKEN)||'';if(!token)throw new Error('Login admin terlebih dahulu.');const r=await fetch(API,{method:'POST',body:new URLSearchParams({action,admin_token:token,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.message||d.error||'Digiflazz Control gagal diproses.');return d}
const date=(v?:string|null)=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(v)):'Belum pernah'
export default function DLavieDigiflazzAdmin(){
 const enabled=new URLSearchParams(location.search).get('support-admin')==='1';const [authed,setAuthed]=useState(()=>!!sessionStorage.getItem(TOKEN)),[open,setOpen]=useState(false),[data,setData]=useState<Status|null>(null),[username,setUsername]=useState(''),[apiKey,setApiKey]=useState(''),[gateway,setGateway]=useState(''),[gatewaySecret,setGatewaySecret]=useState(''),[webhookSecret,setWebhookSecret]=useState(''),[environment,setEnvironment]=useState('testing'),[markupMode,setMarkupMode]=useState('fixed'),[markupValue,setMarkupValue]=useState('500'),[minimum,setMinimum]=useState('300'),[live,setLive]=useState(false),[postpaid,setPostpaid]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>{if(!enabled)return;const t=setInterval(()=>setAuthed(!!sessionStorage.getItem(TOKEN)),700);return()=>clearInterval(t)},[enabled])
 const apply=(s:Status)=>{setData(s);setGateway(s.settings.gateway_url||'');setEnvironment(s.settings.environment||'testing');setMarkupMode(s.settings.markup_mode||'fixed');setMarkupValue(String(s.settings.markup_value??500));setMinimum(String(s.settings.minimum_markup??300));setLive(!!s.settings.live_enabled);setPostpaid(!!s.settings.postpaid_enabled)}
 const load=async()=>{try{apply(await call('status'))}catch(e){setError(e instanceof Error?e.message:'Status gagal dimuat.')}}
 useEffect(()=>{if(open&&authed)void load()},[open,authed])
 const run=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);setError('');setMessage('');try{const d=await fn();setMessage(ok);if(d.settings){const s=await call('status');apply(s)}return d}catch(e){setError(e instanceof Error?e.message:'Operasi gagal.');return null}finally{setBusy(false)}}
 const saveCred=async(e:FormEvent)=>{e.preventDefault();const d=await run(()=>call('save_credentials',{username,api_key:apiKey}),'Credential tersimpan aman di Supabase Vault.');if(d){setApiKey('');await load()}}
 if(!enabled||!authed)return null
 const ready=data?.secrets.username&&data?.secrets.api_key&&data?.secrets.gateway_secret&&!!data?.settings.gateway_url
 return <div className={`dlv-digi-admin${open?' is-open':''}`}><button className="dlv-digi-admin-toggle" onClick={()=>setOpen(v=>!v)}>DIGIFLAZZ <b>{data?.settings.catalog_count||0}</b></button>{open&&<aside><header><div><span>DIGIFLAZZ CONTROL CENTER</span><strong>Catalog · static egress · pricing</strong></div><button onClick={()=>setOpen(false)}>×</button></header><div className="dlv-digi-admin-body"><section className="dlv-digi-health"><i className={ready?'is-on':''}/><div><strong>{ready?'Gateway configuration ready':'Setup belum lengkap'}</strong><span>{data?.settings.live_enabled?'Transaksi aktif':'Transaksi dikunci'} · {data?.settings.environment||'testing'} · {data?.settings.catalog_count||0} SKU · {data?.settings.postpaid_enabled?'Prepaid + tagihan':'Prepaid'}</span></div><button disabled={busy} onClick={()=>void load()}>Refresh</button></section>{error&&<div className="dlv-digi-error">{error}</div>}{message&&<div className="dlv-digi-success">{message}</div>}
 <section><h3>1. Credential Buyer</h3><p>Username dan API Key disimpan di Supabase Vault dan tidak pernah dikirim ke browser user.</p><form onSubmit={saveCred}><input value={username} onChange={e=>setUsername(e.target.value)} placeholder={data?.secrets.username?'Username tersimpan · isi untuk mengganti':'Username API Digiflazz'} autoComplete="off"/><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={data?.secrets.api_key?'API Key tersimpan · isi untuk mengganti':'API Key Digiflazz'} autoComplete="new-password"/><button disabled={busy||username.trim().length<2||apiKey.trim().length<8}>Simpan credential</button></form></section>
 <section><h3>2. Static Egress Gateway</h3><p>Digiflazz membutuhkan request berasal dari IP yang kamu whitelist. GitHub Pages tetap menjadi website DLavie; gateway ini hanya backend outbound dengan IP tetap.</p><div className="dlv-digi-row"><input value={gateway} onChange={e=>setGateway(e.target.value)} placeholder="https://gateway-kamu.example/api/digiflazz-gateway"/><button disabled={busy} onClick={()=>void run(()=>call('save_gateway',{gateway_url:gateway}),'Gateway URL disimpan.')}>Simpan</button></div><div className="dlv-digi-row"><button className="is-secondary" disabled={busy||!ready} onClick={()=>void run(()=>call('test_gateway'),'Static egress gateway merespons dengan benar.')}>Test gateway</button><button className="is-secondary" disabled={busy} onClick={async()=>{const d=await run(()=>call('generate_gateway_secret'),'Gateway secret baru dibuat.');if(d)setGatewaySecret(d.secret||'')}}>Generate secret</button></div>{gatewaySecret&&<div className="dlv-digi-secret"><code>{gatewaySecret}</code><button onClick={()=>void navigator.clipboard.writeText(gatewaySecret)}>Copy</button><small>Simpan sebagai <b>DLAVIE_GATEWAY_SECRET</b> pada layanan Static Egress Gateway. Setelah panel ditutup, nilai ini tidak ditampilkan lagi.</small></div>}</section>
 <section><h3>3. Webhook Digiflazz</h3><p>Webhook menerima update prepaid maupun postpaid secara realtime.</p><code className="dlv-digi-url">https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-digiflazz-webhook</code><button className="is-secondary" disabled={busy} onClick={async()=>{const d=await run(()=>call('generate_webhook_secret'),'Webhook secret baru dibuat.');if(d)setWebhookSecret(d.secret||'')}}>Generate webhook secret</button>{webhookSecret&&<div className="dlv-digi-secret"><code>{webhookSecret}</code><button onClick={()=>void navigator.clipboard.writeText(webhookSecret)}>Copy</button><small>Masukkan sebagai secret Webhook di panel Digiflazz.</small></div>}</section>
 <section><h3>4. Harga & environment</h3><div className="dlv-digi-grid"><label><span>Environment</span><select value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="testing">Testing</option><option value="production">Production</option></select></label><label><span>Markup</span><select value={markupMode} onChange={e=>setMarkupMode(e.target.value)}><option value="fixed">Nominal Rp</option><option value="percent">Persentase %</option></select></label><label><span>Nilai markup</span><input inputMode="decimal" value={markupValue} onChange={e=>setMarkupValue(e.target.value)}/></label><label><span>Minimum markup</span><input inputMode="numeric" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label></div><label className="dlv-digi-check"><input type="checkbox" checked={postpaid} onChange={e=>setPostpaid(e.target.checked)}/><span>Aktifkan katalog & flow Bayar Tagihan</span></label><label className="dlv-digi-check"><input type="checkbox" checked={live} onChange={e=>setLive(e.target.checked)}/><span>Aktifkan transaksi digital</span></label><button disabled={busy} onClick={()=>void run(()=>call('save_settings',{environment,markup_mode:markupMode,markup_value:markupValue,minimum_markup:minimum,postpaid_enabled:String(postpaid),live_enabled:String(live)}),'Pengaturan marketplace disimpan.')}>Simpan pengaturan</button><small>Produk tagihan format khusus seperti PBB, E-Money, dan SAMSAT tetap ditahan sampai form tambahannya tersedia.</small></section>
 <section className="dlv-digi-sync"><h3>5. Sinkron katalog</h3><p>Price list disimpan ke database DLavie. User membaca cache server ini, bukan memanggil API Digiflazz langsung.</p><button disabled={busy||!ready} onClick={()=>void run(()=>call('sync_catalog'),'Katalog Digiflazz selesai disinkronkan.')}>{busy?'Memproses…':'Sync katalog sekarang'}</button><small>Terakhir: {date(data?.settings.last_catalog_sync_at)} · {data?.settings.last_catalog_sync_status||'—'} · {data?.settings.last_catalog_sync_message||'—'}</small></section>
 </div></aside>}</div>
}
