import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import DigitalOrderHistory from './DigitalOrderHistory'
import DigitalReceipt from './DigitalReceipt'
import DigitalBrandIcon,{DigitalCategoryIcon} from './DigitalBrandIcon'
import { detectIndonesianOperator, internationalPhone, isPhoneCategory, isTelcoCategory, localPhone, maskPhone, phoneDigits, targetInputMode } from './DigitalPhoneIntelligence'
import { digitalAuth, digitalCall, digitalExtendedCall, digitalExtendedKind, digitalRoute, digitalStatus, digitalTargetLabel, isDigitalMarket, money, type DigitalIntegration, type DigitalOrder, type DigitalProduct, type DigitalSummary } from './digital-market-api'

const STATE_EVENT='dlavie:state-changed'
type MarketKind='prepaid'|'postpaid'
type ViewMode='grid'|'list'
const routeKind=():MarketKind=>digitalRoute().params.get('kind')==='postpaid'?'postpaid':'prepaid'
const categoryOrder=['Pulsa','Paket Data','PLN','E-Wallet','Voucher & Game','Voucher Operator','Streaming & Hiburan','BPJS','PDAM','Internet & TV','PBB','SAMSAT','Multifinance','Gas','Asuransi','Tagihan Lainnya']
const brandOrder=['Telkomsel','IM3','XL','AXIS','Tri','Smartfren','DANA','OVO','GoPay','ShopeePay','LinkAja','Mobile Legends','Free Fire','PUBG Mobile','Call of Duty Mobile','Honor of Kings','Roblox','Valorant','Genshin Impact','Honkai: Star Rail','Zenless Zone Zero','Arena Breakout','Delta Force','Blood Strike','Wild Rift','League of Legends','FC Mobile','Point Blank']
const idx=(arr:string[],v:string)=>{const i=arr.indexOf(v);return i<0?999:i}
const clean=(v='')=>v.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
const maskValue=(v='')=>{if(!v)return'—';if(/^\+?\d{8,}$/.test(v.replace(/\s/g,'')))return maskPhone(v);if(v.length<=6)return'••••';return `${v.slice(0,3)}••••${v.slice(-3)}`}
const maskSerial=(v='')=>v.length<8?'••••••':`${v.slice(0,5)}••••••${v.slice(-5)}`
const categoryCopy=(value:string)=>{const x=clean(value);if(x.includes('pulsa'))return'Nomor dideteksi otomatis lalu nominal ditampilkan';if(x.includes('paket data'))return'Deteksi operator otomatis lalu pilih paket';if(x==='pln'||x.includes('listrik'))return'Token listrik dan layanan PLN';if(x.includes('wallet'))return'Top up saldo dompet digital';if(x.includes('voucher game'))return'Pilih game dulu, lalu diamonds / points';if(x.includes('voucher operator'))return'Voucher operator yang tersedia';if(x.includes('streaming'))return'Langganan dan voucher hiburan digital';return'Cek pelanggan dan nominal sebelum bayar'}
const brandCopy=(category:string,brand:string)=>{const x=clean(category);if(x.includes('game'))return'Pilih nominal / item';if(x.includes('data'))return'Pilih paket internet';if(x.includes('pulsa'))return'Pilih nominal pulsa';if(x.includes('wallet'))return'Pilih nominal top up';return`Lihat produk ${brand}`}
const friendlyName=(p:DigitalProduct)=>{const name=(p.product_name||p.sku).trim(),b=(p.brand||'').trim();if(!b)return name;const n=clean(name),bb=clean(b);if(n.startsWith(bb+' ')){const words=b.split(/\s+/).length;return name.split(/\s+/).slice(words).join(' ').replace(/^[-–—:·]+\s*/,'').trim()||name}return name}
const detailRows=(detail?:Record<string,unknown>|null)=>{if(!detail)return[] as Array<[string,string]>;const labels:Record<string,string>={tarif:'Tarif',daya:'Daya',lembar_tagihan:'Lembar tagihan',alamat:'Alamat',jatuh_tempo:'Jatuh tempo',jumlah_peserta:'Jumlah peserta',item_name:'Item',tahun_pajak:'Tahun pajak',kelurahan:'Kelurahan',kecamatan:'Kecamatan',kab_kota:'Kab/Kota',nomor_polisi:'Nomor polisi',merek_kb:'Merek kendaraan',model_kb:'Model kendaraan',tahun_buatan:'Tahun kendaraan'};return Object.entries(detail).filter(([k,v])=>k!=='detail'&&!k.startsWith('_dlavie_')&&v!=null&&typeof v!=='object').slice(0,8).map(([k,v])=>[labels[k]||k.replaceAll('_',' '),String(v)] as [string,string])}

function ViewSwitch({value,onChange}:{value:ViewMode;onChange:(v:ViewMode)=>void}){return <div className="dlv21-view" role="group" aria-label="Mode tampilan"><button className={value==='grid'?'is-active':''} onClick={()=>onChange('grid')} aria-label="Grid"><svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg></button><button className={value==='list'?'is-active':''} onClick={()=>onChange('list')} aria-label="List"><svg viewBox="0 0 24 24"><path d="M9 6h11M9 12h11M9 18h11"/><circle cx="5" cy="6" r="1"/><circle cx="5" cy="12" r="1"/><circle cx="5" cy="18" r="1"/></svg></button></div>}

export default function DLavieDigitalMarketV22(){
 const [active,setActive]=useState(isDigitalMarket),[summary,setSummary]=useState<DigitalSummary[]>([]),[integration,setIntegration]=useState<DigitalIntegration|null>(null)
 const [kind,setKind]=useState<MarketKind>(routeKind),[category,setCategory]=useState(''),[brand,setBrand]=useState(''),[query,setQuery]=useState(''),[products,setProducts]=useState<DigitalProduct[]>([])
 const [selected,setSelected]=useState<DigitalProduct|null>(null),[target,setTarget]=useState(''),[telcoTarget,setTelcoTarget]=useState(''),[extraIdentity,setExtraIdentity]=useState(''),[extraAmount,setExtraAmount]=useState(''),[extraYear,setExtraYear]=useState('')
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<DigitalOrder|null>(null),[privateReceipt,setPrivateReceipt]=useState<DigitalOrder|null>(null),[orders,setOrders]=useState<DigitalOrder[]>([]),[historyOpen,setHistoryOpen]=useState(false)
 const [balance,setBalance]=useState(()=>Number(localStorage.getItem('dlavie-balance')||0)),[sandboxBalance,setSandboxBalance]=useState<number|null>(null),[view,setView]=useState<ViewMode>(()=>localStorage.getItem('dlavie-market-view')==='list'?'list':'grid')
 const [confirmedData,setConfirmedData]=useState(false),[acceptedPolicy,setAcceptedPolicy]=useState(false)
 const nokos=digitalRoute().name==='market'&&digitalRoute().params.get('mode')==='nokos',sandbox=integration?.environment==='sandbox'
 const groups=useMemo(()=>summary.filter(x=>x.product_kind===kind).sort((a,b)=>idx(categoryOrder,a.category)-idx(categoryOrder,b.category)||a.category.localeCompare(b.category,'id')),[summary,kind])
 const current=groups.find(x=>x.category===category),sortedBrands=useMemo(()=>[...(current?.brands||[])].filter(Boolean).sort((a,b)=>idx(brandOrder,a)-idx(brandOrder,b)||a.localeCompare(b,'id')),[current])
 const filteredBrands=useMemo(()=>{const q=clean(query),all=q?sortedBrands.filter(x=>clean(x).includes(q)):sortedBrands;return all.slice(0,q?120:64)},[sortedBrands,query])
 const telcoFlow=isTelcoCategory(category),detectedOperator=detectIndonesianOperator(telcoTarget),brandHub=!!category&&!brand&&sortedBrands.length>1&&!telcoFlow
 const extended=digitalExtendedKind(selected),extraReady=extended==='emoney'?Number(extraAmount)>=1000:extended==='samsat'?extraIdentity.trim().length>=4:true
 const effectiveBalance=sandbox?(sandboxBalance??1000000):balance,prepaidCount=summary.filter(x=>x.product_kind==='prepaid').reduce((n,x)=>n+x.product_count,0),postpaidCount=summary.filter(x=>x.product_kind==='postpaid').reduce((n,x)=>n+x.product_count,0)
 const inputPhone=!!selected&&isPhoneCategory(selected.category),targetDigits=inputPhone?phoneDigits(target):target.trim(),targetReady=inputPhone?targetDigits.length>=9:targetDigits.length>=3
 const checkoutOperator=selected&&isTelcoCategory(selected.category)?detectIndonesianOperator(target):null,operatorMismatch=!!(selected&&isTelcoCategory(selected.category)&&checkoutOperator&&checkoutOperator!==selected.brand)

 const resetConsent=()=>{setConfirmedData(false);setAcceptedPolicy(false)}
 const resetExtras=()=>{setExtraIdentity('');setExtraAmount('');setExtraYear('');resetConsent()}
 const resetCheckout=()=>{setSelected(null);setReceipt(null);setTarget('');resetExtras()}
 const loadSummary=useCallback(async()=>{try{const d=await digitalCall('summary');setSummary((d.summary||[]).map((x:any)=>({...x,product_count:Number(x.product_count||0),min_price:Number(x.min_price||0),max_price:Number(x.max_price||0),brands:Array.isArray(x.brands)?x.brands:[]})));setIntegration(d.integration||null)}catch(e){setError(e instanceof Error?e.message:'Katalog belum dapat dimuat.')}},[])
 const loadProducts=useCallback(async(k:MarketKind,cat:string,br:string,q:string)=>{if(!cat)return;setLoading(true);setError('');try{const d=await digitalCall('products',{category:cat,brand:br,q,kind:k,limit:'100'});setProducts(d.products||[])}catch(e){setError(e instanceof Error?e.message:'Produk belum dapat dimuat.')}finally{setLoading(false)}},[])
 const loadHistory=useCallback(async()=>{const a=digitalAuth();if(!a.wallet_token||!a.user_id)return;try{const d=await digitalCall('history',a);setOrders(d.orders||[]);if(typeof d.balance==='number'){setBalance(d.balance);localStorage.setItem('dlavie-balance',String(d.balance))}if(typeof d.sandbox_balance==='number')setSandboxBalance(d.sandbox_balance);window.dispatchEvent(new CustomEvent(STATE_EVENT))}catch{}},[])
 useEffect(()=>{const sync=()=>{const yes=isDigitalMarket();setActive(yes);if(yes&&!digitalRoute().params.get('mode'))setKind(routeKind());document.documentElement.toggleAttribute('data-digital-market',yes)};sync();window.addEventListener('hashchange',sync);return()=>{window.removeEventListener('hashchange',sync);document.documentElement.removeAttribute('data-digital-market')}},[])
 useEffect(()=>{if(active){void loadSummary();void loadHistory()}},[active,loadSummary,loadHistory])
 useEffect(()=>{if(!active||!category||brandHub||(telcoFlow&&!brand))return;const t=window.setTimeout(()=>void loadProducts(kind,category,brand,query),180);return()=>window.clearTimeout(t)},[active,category,brand,query,kind,brandHub,telcoFlow,loadProducts])
 useEffect(()=>{if(!active||category||!groups.length)return;const requested=(digitalRoute().params.get('category')||'').trim().toLowerCase();if(!requested)return;const match=groups.find(x=>x.category.toLowerCase()===requested||x.category.toLowerCase().includes(requested)||requested.includes(x.category.toLowerCase()));if(match)setCategory(match.category)},[active,category,groups])
 useEffect(()=>{if(!telcoFlow||brand||phoneDigits(telcoTarget).length<3||!detectedOperator)return;if(sortedBrands.includes(detectedOperator)){setBrand(detectedOperator);setQuery('');setProducts([])}},[telcoFlow,brand,telcoTarget,detectedOperator,sortedBrands])
 useEffect(()=>{document.documentElement.toggleAttribute('data-market-sheet',!!selected||!!receipt);return()=>document.documentElement.removeAttribute('data-market-sheet')},[selected,receipt])
 const applyBalances=(d:any)=>{if(sandbox){if(typeof d?.sandbox_balance==='number')setSandboxBalance(d.sandbox_balance);else if(typeof d?.balance==='number')setSandboxBalance(d.balance)}else if(typeof d?.balance==='number'){setBalance(d.balance);localStorage.setItem('dlavie-balance',String(d.balance))}window.dispatchEvent(new CustomEvent(STATE_EVENT))}
 const setViewMode=(next:ViewMode)=>{setView(next);localStorage.setItem('dlavie-market-view',next)}
 const chooseKind=(value:MarketKind)=>{setKind(value);setCategory('');setBrand('');setTelcoTarget('');setQuery('');setProducts([]);resetCheckout();const next=value==='postpaid'?'#/market?kind=postpaid':'#/market';if(location.hash!==next)location.hash=next}
 const chooseCategory=(c:string)=>{setCategory(c);setBrand('');setTelcoTarget('');setQuery('');setProducts([]);resetCheckout()}
 const chooseBrand=(b:string)=>{setBrand(b);setQuery('');setProducts([]);resetCheckout()}
 const chooseProduct=(p:DigitalProduct)=>{setSelected(p);setReceipt(null);setTarget(isTelcoCategory(p.category)?phoneDigits(telcoTarget):'');resetExtras()}
 const back=()=>{if(brand){setBrand('');setQuery('');setProducts([]);resetCheckout()}else{setCategory('');setTelcoTarget('');setQuery('');setProducts([]);resetCheckout()}}
 const purchase=async(e:FormEvent)=>{e.preventDefault();if(!selected||busy||!targetReady||!extraReady||operatorMismatch||!confirmedData||!acceptedPolicy)return;setBusy(true);setError('');try{const auth=digitalAuth();const finalTarget=isPhoneCategory(selected.category)?localPhone(target):target.trim();let d:any;if(kind==='postpaid'&&extended){const customer=extended==='samsat'?`${finalTarget},${extraIdentity.trim()}`:finalTarget;const extra:Record<string,string>={...auth,sku:selected.sku,customer_no:customer};if(extended==='emoney')extra.amount=String(Math.round(Number(extraAmount)));if(extended==='pbb'&&extraYear.trim())extra.year=extraYear.trim();d=await digitalExtendedCall(extra)}else d=await digitalCall(kind==='postpaid'?'inquiry_postpaid':'purchase',{...auth,sku:selected.sku,customer_no:finalTarget});setReceipt(d.order);setSelected(null);applyBalances(d);await loadHistory()}catch(e){setError(e instanceof Error?e.message:'Transaksi belum dapat diproses.')}finally{setBusy(false)}}
 const payPostpaid=async(ref:string)=>{if(busy)return;setBusy(true);setError('');try{const d=await digitalCall('pay_postpaid',{...digitalAuth(),ref_id:ref});setReceipt(d.order);applyBalances(d);setHistoryOpen(false);await loadHistory()}catch(e){setError(e instanceof Error?e.message:'Pembayaran tagihan belum dapat diproses.')}finally{setBusy(false)}}
 const checkStatus=async(ref:string)=>{if(busy)return;setBusy(true);setError('');try{const d=await digitalCall('status',{...digitalAuth(),ref_id:ref});setReceipt(d.order);applyBalances(d);await loadHistory()}catch(e){setError(e instanceof Error?e.message:'Status belum dapat diperbarui.')}finally{setBusy(false)}}
 if(nokos)return <button className="dlv-digital-return" onClick={()=>{location.hash='#/market'}}>← Digital Market</button>
 if(!active)return null
 const billRows=detailRows(receipt?.inquiry_detail),displayBalance=sandbox?(sandboxBalance??1000000):balance

 return <main className="dlv-digital-market dlv21-market dlv22-market"><div className="dlv21-shell">
  <header className="dlv21-hero"><div><span>DIGITAL MARKET</span><h1>Pilih lebih yakin.<br/>Bayar tanpa salah tujuan.</h1><p>Nomor, provider, produk dan nominal dicek bertahap sebelum transaksi dikirim.</p></div><aside><small>{sandbox?'SALDO TES':'SALDO WALLET'}</small><strong>{money.format(displayBalance)}</strong>{sandbox?<em>Wallet asli tetap {money.format(balance)}</em>:<button onClick={()=>document.querySelector<HTMLButtonElement>('.balance-pill')?.click()}>Tambah saldo</button>}</aside></header>
  <div className="dlv21-status"><div><i className={sandbox||integration?.enabled?'is-on':''}/><b>{sandbox?'Sandbox DLavie':integration?.enabled?'H2H.id Production':'Katalog H2H.id'}</b><span>{integration?.catalog_count||0} SKU tersinkron</span></div><button onClick={()=>setHistoryOpen(true)}>Pesanan {orders.length?`· ${orders.length}`:''}</button></div>
  {sandbox&&<div className="dlv21-sandbox-inline"><b>SANDBOX</b><span>HCoin dan Wallet asli tidak dipotong.</span></div>}{error&&<div className="dlv21-alert">{error}<button onClick={()=>setError('')}>×</button></div>}
  {!category?<section className="dlv21-section"><div className="dlv21-head"><div><span>LAYANAN</span><h2>Pilih kebutuhan</h2></div><ViewSwitch value={view} onChange={setViewMode}/></div><div className="dlv21-kind"><button className={kind==='prepaid'?'is-active':''} onClick={()=>chooseKind('prepaid')}><DigitalCategoryIcon value="Pulsa dan Data"/><span><b>Produk Instan</b><small>{prepaidCount} produk aktif</small></span></button><button className={kind==='postpaid'?'is-active':''} disabled={!integration?.postpaid_enabled} onClick={()=>chooseKind('postpaid')}><DigitalCategoryIcon value="Bayar Tagihan"/><span><b>Bayar Tagihan</b><small>{integration?.postpaid_enabled?`${postpaidCount} layanan`:'Belum diaktifkan'}</small></span></button></div><div className={`dlv21-category-grid is-${view}`}><button className="is-nokos" onClick={()=>{location.hash='#/market?mode=nokos'}}><DigitalCategoryIcon value="Nomor Virtual"/><span><b>Nomor Virtual</b><small>Layanan nomor & verifikasi</small></span><strong>→</strong></button>{groups.map(x=><button key={`${kind}-${x.category}`} onClick={()=>chooseCategory(x.category)}><DigitalCategoryIcon value={x.category}/><span><b>{x.category}</b><small>{categoryCopy(x.category)}</small><em>{x.product_count.toLocaleString('id-ID')} produk</em></span><strong>→</strong></button>)}</div></section>:
  <section className="dlv21-section dlv21-catalog"><div className="dlv21-breadcrumb"><button onClick={back}>←</button><span>Digital Market</span><b>/</b><span>{category}</span>{brand&&<><b>/</b><strong>{brand}</strong></>}</div>
   {telcoFlow&&!brand?<><div className="dlv22-number-first"><div><span>LANGKAH 1 · NOMOR TUJUAN</span><h2>Masukkan nomor {category==='Pulsa'?'pulsa':'paket data'}</h2><p>DLavie mendeteksi operator dari prefix nomor dan hanya menampilkan produk provider yang sesuai.</p></div><label><span className="dlv22-country">🇮🇩 +62</span><input autoFocus inputMode="numeric" pattern="[0-9]*" value={phoneDigits(telcoTarget)} onChange={e=>setTelcoTarget(phoneDigits(e.target.value))} placeholder="812 3456 7890" autoComplete="tel-national"/></label><div className={`dlv22-operator-result ${detectedOperator?'is-found':''}`}>{detectedOperator?<><DigitalBrandIcon brand={detectedOperator} category={category}/><span><small>OPERATOR TERDETEKSI</small><b>{detectedOperator}</b><em>{internationalPhone(telcoTarget)}</em></span><strong>Produk dibuka otomatis →</strong></>:<><DigitalCategoryIcon value="Paket Data"/><span><small>MENUNGGU PREFIX</small><b>Operator akan muncul otomatis</b><em>Contoh: 812… Telkomsel</em></span></>}</div></div></>:
   brandHub?<><div className="dlv21-head"><div><span>{category==='Voucher & Game'?'PILIH GAME':'PILIH BRAND'}</span><h2>{category}</h2><p>{category==='Voucher & Game'?'Setiap game dipisahkan supaya item tidak bercampur.':'Pilih provider terlebih dahulu.'}</p></div></div><div className="dlv21-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={category==='Voucher & Game'?'Cari Free Fire, Mobile Legends, Roblox…':'Cari brand / provider…'}/><span>{sortedBrands.length} pilihan</span></div><div className="dlv21-brand-grid">{filteredBrands.map(x=><button key={x} onClick={()=>chooseBrand(x)}><DigitalBrandIcon brand={x} category={category}/><span><b>{x}</b><small>{brandCopy(category,x)}</small></span><strong>→</strong></button>)}</div>{filteredBrands.length===0&&<div className="dlv21-empty">Brand atau game tidak ditemukan.</div>}</>:
   <>{telcoFlow&&brand&&<div className="dlv22-recipient-strip"><div><DigitalBrandIcon brand={brand} category={category}/><span><small>NOMOR TUJUAN · {brand}</small><b>{internationalPhone(telcoTarget)}</b></span></div><button onClick={()=>{setBrand('');setProducts([]);resetCheckout()}}>Ganti nomor</button></div>}<div className="dlv21-head"><div><span>{brand||category}</span><h2>{brand||category}</h2><p>Pilih produk untuk membuka pemeriksaan akhir sebelum transaksi.</p></div><ViewSwitch value={view} onChange={setViewMode}/></div><div className="dlv21-product-tools"><button onClick={()=>{setBrand('');setQuery('');setProducts([])}} disabled={sortedBrands.length<=1||telcoFlow}>⌁ {brand||'Semua brand'}</button><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nominal atau paket…"/></div><div className={`dlv21-product-grid is-${view}`}>{loading?<div className="dlv21-loading">Memuat produk…</div>:products.map(p=><button key={p.sku} onClick={()=>chooseProduct(p)}><DigitalBrandIcon brand={p.brand} category={p.category}/><span><small>{p.brand}</small><b>{friendlyName(p)}</b><em>{p.product_type?.replaceAll('_',' ')||p.category}</em></span><strong>{kind==='postpaid'?'Cek tagihan':money.format(p.sell_price)}</strong></button>)}</div>{!loading&&!products.length&&<div className="dlv21-empty">Tidak ada produk untuk filter ini.</div>}</>}
  </section>}
 </div>

 {(selected||receipt)&&<div className="dlv21-sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)resetCheckout()}}><aside className="dlv21-sheet dlv22-sheet" role="dialog" aria-modal="true"><button className="dlv21-sheet-close" disabled={busy} onClick={resetCheckout}>×</button>{selected?<form onSubmit={purchase}><div className="dlv21-sheet-kicker">{sandbox?'SANDBOX · PEMERIKSAAN AKHIR':kind==='postpaid'?'CEK TAGIHAN':'PEMERIKSAAN AKHIR'}</div><div className="dlv21-sheet-brand"><DigitalBrandIcon brand={selected.brand} category={selected.category}/><div><small>{selected.brand}</small><h3>{friendlyName(selected)}</h3><code>{selected.sku}</code></div></div>
   <label><span>{digitalTargetLabel(selected.category,selected.brand)}</span>{isPhoneCategory(selected.category)?<div className="dlv22-phone-field"><span>+62</span><input inputMode="numeric" pattern="[0-9]*" value={phoneDigits(target)} onChange={e=>{setTarget(phoneDigits(e.target.value));resetConsent()}} placeholder="81234567890" autoComplete="tel-national"/></div>:<input inputMode={targetInputMode(selected.category,selected.brand)} pattern={targetInputMode(selected.category,selected.brand)==='numeric'?'[0-9]*':undefined} value={target} onChange={e=>{setTarget(targetInputMode(selected.category,selected.brand)==='numeric'?e.target.value.replace(/\D/g,''):e.target.value);resetConsent()}} placeholder={selected.category==='Voucher & Game'?'Masukkan User ID / Player ID':'Masukkan tujuan dengan teliti'} autoComplete="off"/>}</label>
   {isPhoneCategory(selected.category)&&<div className="dlv22-detected"><span>Nomor lengkap</span><b>{internationalPhone(target)}</b>{checkoutOperator&&<em>Operator: {checkoutOperator}</em>}</div>}{operatorMismatch&&<div className="dlv22-mismatch">Nomor terdeteksi <b>{checkoutOperator}</b>, tetapi produk ini untuk <b>{selected.brand}</b>. Ganti nomor atau pilih produk operator yang sesuai.</div>}
   {extended==='samsat'&&<label><span>Nomor identitas</span><input inputMode="numeric" value={extraIdentity} onChange={e=>{setExtraIdentity(e.target.value.replace(/\D/g,''));resetConsent()}} required/></label>}{extended==='emoney'&&<label><span>Nominal E-Money</span><input inputMode="numeric" value={extraAmount} onChange={e=>{setExtraAmount(e.target.value.replace(/\D/g,''));resetConsent()}} placeholder="25000" required/><small>{extraAmount?money.format(Number(extraAmount)):'Minimal Rp1.000'}</small></label>}{extended==='pbb'&&<label><span>Tahun pajak <i>opsional</i></span><input inputMode="numeric" maxLength={4} value={extraYear} onChange={e=>{setExtraYear(e.target.value.replace(/\D/g,'').slice(0,4));resetConsent()}} placeholder="2026"/></label>}
   {selected.description&&selected.description!==selected.product_name&&<p className="dlv21-desc">{selected.description}</p>}{kind==='prepaid'&&<div className="dlv21-total"><span>Total</span><strong>{money.format(selected.sell_price)}</strong></div>}
   <div className="dlv22-review"><b>Periksa sebelum membeli</b><p><span>Produk</span><strong>{friendlyName(selected)}</strong></p><p><span>Tujuan</span><strong>{isPhoneCategory(selected.category)?internationalPhone(target):target||'Belum diisi'}</strong></p><p><span>Total</span><strong>{kind==='prepaid'?money.format(selected.sell_price):'Ditentukan setelah inquiry'}</strong></p></div>
   <div className="dlv22-consent"><label><input type="checkbox" checked={confirmedData} onChange={e=>setConfirmedData(e.target.checked)}/><span><b>Saya sudah memeriksa data.</b> Nomor/User ID, provider, produk dan nominal di atas sudah benar.</span></label><label><input type="checkbox" checked={acceptedPolicy} onChange={e=>setAcceptedPolicy(e.target.checked)}/><span><b>Saya menyetujui kebijakan transaksi digital.</b> Transaksi yang sudah berhasil diproses tidak dapat dibatalkan hanya karena kesalahan nomor/User ID atau salah memilih produk dari pihak pengguna.</span></label></div>
   <button className="dlv21-primary" disabled={busy||!targetReady||!extraReady||operatorMismatch||!confirmedData||!acceptedPolicy}>{busy?'Memproses…':kind==='postpaid'?'Cek tagihan':sandbox?'Tes di Sandbox':'Bayar dengan Wallet'}<b>→</b></button><em className="dlv21-safe">{sandbox?'HCoin dan Wallet asli tidak dipotong.':'Server memverifikasi harga, saldo dan idempotency sekali lagi.'}</em></form>:receipt?<div className="dlv21-receipt dlv22-result"><div className="dlv21-sheet-kicker">{sandbox?'HASIL SANDBOX':'TRANSAKSI DIGITAL'}</div><h3>{digitalStatus(receipt.status)}</h3><code>{receipt.ref_id}</code><div className="dlv21-receipt-product"><DigitalBrandIcon brand={receipt.brand} category={receipt.category}/><span><small>{receipt.brand}</small><b>{receipt.product_name}</b></span></div><p><span>Tujuan</span><b>{maskValue(receipt.customer_no)}</b></p>{receipt.customer_name&&<p><span>Pelanggan</span><b>{receipt.customer_name}</b></p>}{receipt.period&&<p><span>Periode</span><b>{receipt.period}</b></p>}{billRows.map(([k,v])=><p key={k}><span>{k}</span><b>{v}</b></p>)}<div className="dlv21-total"><span>Total</span><strong>{money.format(receipt.sell_price)}</strong></div>{receipt.message&&<div className="dlv21-receipt-message">{receipt.message}</div>}{receipt.serial_number&&<div className="dlv21-sn"><small>SN / TOKEN · DISAMARKAN</small><b>{maskSerial(receipt.serial_number)}</b></div>}<button className="dlv22-receipt-open" onClick={()=>setPrivateReceipt(receipt)}>▣ Buka Struk Lengkap</button>{receipt.status==='inquired'&&<button className="dlv21-primary" disabled={busy||effectiveBalance<receipt.sell_price} onClick={()=>void payPostpaid(receipt.ref_id)}>{busy?'Memproses…':effectiveBalance<receipt.sell_price?'Saldo tidak cukup':sandbox?'Bayar di Sandbox':'Bayar dengan Wallet'}</button>}{(receipt.status==='pending'||receipt.status==='reserved')&&<button className="dlv21-primary" disabled={busy} onClick={()=>void checkStatus(receipt.ref_id)}>Cek status</button>}</div>:null}</aside></div>}
 <DigitalOrderHistory open={historyOpen} orders={orders} busy={busy} onClose={()=>setHistoryOpen(false)} onCheck={ref=>void checkStatus(ref)} onPay={ref=>void payPostpaid(ref)} onReceipt={o=>{setHistoryOpen(false);setPrivateReceipt(o)}}/>
 <DigitalReceipt order={privateReceipt} onClose={()=>setPrivateReceipt(null)}/>
 </main>
}
