import { FormEvent, useEffect, useState } from 'react'
const API='https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-digiflazz-admin',RECON_API='https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-digiflazz-reconcile',TOKEN='dlavie-admin-support-session-v1'
type Settings={environment:string;markup_mode:string;markup_value:number;minimum_markup:number;live_enabled:boolean;gateway_url?:string|null;catalog_count:number;postpaid_enabled:boolean;last_catalog_sync_at?:string|null;last_catalog_sync_status?:string|null;last_catalog_sync_message?:string|null}
type Readiness={credentials:boolean;gateway:boolean;webhook:boolean;catalog:boolean;testing_safe:boolean;production_safe:boolean}
type Status={settings:Settings;secrets:{username:boolean;api_key:boolean;gateway_secret:boolean;webhook_secret:boolean};readiness?:Readiness}
type ReconOrder={ref_id:string;product_kind:string;product_name:string;customer_no:string;sell_price:number;status:string;message?:string|null;updated_at:string;last_reconciled_at?:string|null;reconciliation_attempts?:number;reconciliation_note?:string|null;needs_action?:boolean}
type ReconData={orders:ReconOrder[];summary:{total:number;created:number;reserved:number;pending:number;needs_action:number}}
async function call(action:string,extra:Record<string,string>={}){const token=sessionStorage.getItem(TOKEN)||'';if(!token)throw new Error('Login admin terlebih dahulu.');const r=await fetch(API,{method:'POST',body:new URLSearchParams({action,admin_token:token,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.message||d.error||'Digiflazz Control gagal diproses.');return d}
async function reconcileCall(action:string,extra:Record<string,string>={}){const token=sessionStorage.getItem(TOKEN)||'';if(!token)throw new Error('Login admin terlebih dahulu.');const r=await fetch(RECON_API,{method:'POST',body:new URLSearchParams({action,admin_token:token,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.message||d.error||'Reconciliation gagal diproses.');return d}
const date=(v?:string|null)=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(v)):'Belum pernah'
const rupiah=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0})
const emptyRecon:ReconData={orders:[],summary:{total:0,created:0,reserved:0,pending:0,needs_action:0}}
export default function DLavieDigiflazzAdmin(){
 const enabled=new URLSearchParams(location.search).get('support-admin')==='1';const [authed,setAuthed]=useState(()=>!!sessionStorage.getItem(TOKEN)),[open,setOpen]=useState(false),[data,setData]=useState<Status|null>(null),[recon,setRecon]=useState<ReconData>(emptyRecon),[username,setUsername]=useState(''),[apiKey,setApiKey]=useState(''),[gateway,setGateway]=useState(''),[gatewaySecret,setGatewaySecret]=useState(''),[webhookSecret,setWebhookSecret]=useState(''),[environment,setEnvironment]=useState('testing'),[markupMode,setMarkupMode]=useState('fixed'),[markupValue,setMarkupValue]=useState('500'),[minimum,setMinimum]=useState('300'),[live,setLive]=useState(false),[postpaid,setPostpaid]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>{if(!enabled)return;const t=setInterval(()=>setAuthed(!!sessionStorage.getItem(TOKEN)),700);return()=>clearInterval(t)},[enabled])
 const apply=(s:Status)=>{setData(s);setGateway(s.settings.gateway_url||'');setEnvironment(s.settings.environment||'testing');setMarkupMode(s.settings.markup_mode||'fixed');setMarkupValue(String(s.settings.markup_value??500));setMinimum(String(s.settings.minimum_markup??300));setLive(!!s.settings.live_enabled);setPostpaid(!!s.settings.postpaid_enabled)}
 const load=async()=>{try{apply(await call('status'))}catch(e){setError(e instanceof Error?e.message:'Status gagal dimuat.')}}
 const loadRecon=async()=>{try{const d=await reconcileCall('queue');setRecon({orders:d.orders||[],summary:d.summary||emptyRecon.summary})}catch(e){setError(e instanceof Error?e.message:'Reconciliation queue gagal dimuat.')}}
 useEffect(()=>{if(open&&authed){void load();void loadRecon()}},[open,authed])
 const run=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);setError('');setMessage('');try{const d=await fn();setMessage(ok);if(d.settings){const s=await call('status');apply(s)}return d}catch(e){setError(e instanceof Error?e.message:'Operasi gagal.');return null}finally{setBusy(false)}}
 const runRecon=async(action:'reconcile'|'reconcile_stale',extra:Record<string,string>,ok:string)=>{setBusy(true);setError('');setMessage('');try{const d=await reconcileCall(action,extra);setMessage(ok);if(d.queue)setRecon(d.queue);else await loadRecon();return d}catch(e){setError(e instanceof Error?e.message:'Reconciliation gagal.');return null}finally{setBusy(false)}}
 const saveCred=async(e:FormEvent)=>{e.preventDefault();const d=await run(()=>call('save_credentials',{username,api_key:apiKey}),'Credential tersimpan aman di Supabase Vault.');if(d){setApiKey('');await load()}}
 if(!enabled||!authed)return null
 const gatewayReady=data?.readiness?.gateway??(!!data?.secrets.username&&!!data?.secrets.api_key&&!!data?.secrets.gateway_secret&&!!data?.settings.gateway_url),catalogReady=data?.readiness?.catalog??!!data?.settings.catalog_count,webhookReady=data?.readiness?.webhook??!!data?.secrets.webhook_secret,testingReady=data?.readiness?.testing_safe??(gatewayReady&&catalogReady),productionReady=data?.readiness?.production_safe??(gatewayReady&&catalogReady&&webhookReady),currentReady=environment==='production'?productionReady:testingReady
 return <div className={`dlv-digi-admin${open?' is-open':''}`}><button className="dlv-digi-admin-toggle" onClick={()=>setOpen(v=>!v)}>DIGIFLAZZ <b>{data?.settings.catalog_count||0}</b></button>{open&&<aside><header><div><span>DIGIFLAZZ CONTROL CENTER</span><strong>Catalog · static egress · pricing · reconciliation</strong></div><button onClick={()=>setOpen(false)}>×</button></header><div className="dlv-digi-admin-body"><section className="dlv-digi-health"><i className={currentReady?'is-on':''}/><div><strong>{currentReady?(environment==='production'?'Production siap diaktifkan':'Testing siap dijalankan'):'Setup belum lengkap'}</strong><span>{data?.settings.live_enabled?'Transaksi aktif':'Transaksi dikunci'} · {data?.settings.environment||'testing'} · {data?.settings.catalog_count||0} SKU · Gateway {gatewayReady?'✓':'—'} · Webhook {webhookReady?'✓':'—'} · Katalog {catalogReady?'✓':'—'}</span></div><button disabled={busy} onClick={()=>{void load();void loadRecon()}}>Refresh</button></section>{error&&<div className="dlv-digi-error">{error}</div>}{message&&<div className="dlv-digi-success">{message}</div>}
 <section><h3>1. Credential Buyer</h3><p>Username dan API Key disimpan di Supabase Vault dan tidak pernah dikirim ke browser user.</p><form onSubmit={saveCred}><input value={username} onChange={e=>setUsername(e.target.value)} placeholder={data?.secrets.username?'Username tersimpan · isi untuk mengganti':'Username API Digiflazz'} autoComplete="off"/><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={data?.secrets.api_key?'API Key tersimpan · isi untuk mengganti':'API Key Digiflazz'} autoComplete="new-password"/><button disabled={busy||username.trim().length<2||apiKey.trim().length<8}>Simpan credential</button></form></section>
 <section><h3>2. Static Egress Gateway</h3><p>Digiflazz membutuhkan request berasal dari IP yang kamu whitelist. GitHub Pages tetap menjadi website DLavie; gateway ini hanya backend outbound dengan IP tetap.</p><div className="dlv-digi-row"><input value={gateway} onChange={e=>setGateway(e.target.value)} placeholder="https://gateway-kamu.example/api/digiflazz-gateway"/><button disabled={busy} onClick={()=>void run(()=>call('save_gateway',{gateway_url:gateway}),'Gateway URL disimpan.')}>Simpan</button></div><div className="dlv-digi-row"><button className="is-secondary" disabled={busy||!gatewayReady} onClick={()=>void run(()=>call('test_gateway'),'Static egress gateway merespons dengan benar.')}>Test gateway</button><button className="is-secondary" disabled={busy} onClick={async()=>{const d=await run(()=>call('generate_gateway_secret'),'Gateway secret baru dibuat.');if(d)setGatewaySecret(d.secret||'')}}>Generate secret</button></div>{gatewaySecret&&<div className="dlv-digi-secret"><code>{gatewaySecret}</code><button onClick={()=>void navigator.clipboard.writeText(gatewaySecret)}>Copy</button><small>Simpan sebagai <b>DLAVIE_GATEWAY_SECRET</b> pada layanan Static Egress Gateway. Setelah panel ditutup, nilai ini tidak ditampilkan lagi.</small></div>}</section>
 <section><h3>3. Webhook Digiflazz</h3><p>Webhook menerima update prepaid maupun postpaid secara realtime. Production tidak dapat diaktifkan sebelum secret webhook tersedia.</p><code className="dlv-digi-url">https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-digiflazz-webhook</code><button className="is-secondary" disabled={busy} onClick={async()=>{const d=await run(()=>call('generate_webhook_secret'),'Webhook secret baru dibuat.');if(d)setWebhookSecret(d.secret||'')}}>Generate webhook secret</button>{webhookSecret&&<div className="dlv-digi-secret"><code>{webhookSecret}</code><button onClick={()=>void navigator.clipboard.writeText(webhookSecret)}>Copy</button><small>Masukkan sebagai secret Webhook di panel Digiflazz.</small></div>}</section>
 <section><h3>4. Harga & environment</h3><div className="dlv-digi-grid"><label><span>Environment</span><select value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="testing">Testing</option><option value="production">Production</option></select></label><label><span>Markup</span><select value={markupMode} onChange={e=>setMarkupMode(e.target.value)}><option value="fixed">Nominal Rp</option><option value="percent">Persentase %</option></select></label><label><span>Nilai markup</span><input inputMode="decimal" value={markupValue} onChange={e=>setMarkupValue(e.target.value)}/></label><label><span>Minimum markup</span><input inputMode="numeric" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label></div><label className="dlv-digi-check"><input type="checkbox" checked={postpaid} onChange={e=>setPostpaid(e.target.checked)}/><span>Aktifkan katalog & flow Bayar Tagihan</span></label><label className="dlv-digi-check"><input type="checkbox" checked={live} onChange={e=>setLive(e.target.checked)}/><span>Aktifkan transaksi digital</span></label><button disabled={busy} onClick={()=>void run(()=>call('save_settings',{environment,markup_mode:markupMode,markup_value:markupValue,minimum_markup:minimum,postpaid_enabled:String(postpaid),live_enabled:String(live)}),'Pengaturan marketplace disimpan.')}>Simpan pengaturan</button><small>{environment==='production'?'Production membutuhkan credential + gateway + webhook + katalog sebelum transaksi dapat dibuka.':'Testing membutuhkan credential + gateway + katalog sebelum transaksi dapat dibuka.'} Produk format khusus seperti PBB, E-Money, dan SAMSAT tetap ditahan sampai form tambahannya tersedia.</small></section>
 <section className="dlv-digi-sync"><h3>5. Sinkron katalog</h3><p>Price list disimpan ke database DLavie. User membaca cache server ini, bukan memanggil API Digiflazz langsung.</p><button disabled={busy||!gatewayReady} onClick={()=>void run(()=>call('sync_catalog'),'Katalog Digiflazz selesai disinkronkan.')}>{busy?'Memproses…':'Sync katalog sekarang'}</button><small>Terakhir: {date(data?.settings.last_catalog_sync_at)} · {data?.settings.last_catalog_sync_status||'—'} · {data?.settings.last_catalog_sync_message||'—'}</small></section>
 <section className="dlv-digi-reconcile"><h3>6. Reconciliation Center</h3><p>Order created, reserved, atau pending yang tertinggal dapat diperiksa tanpa mengirim transaksi baru. Cek supplier hanya dilakukan setelah cooldown dan transaksi lama tidak disentuh melewati batas aman.</p><div className="dlv-digi-reconcile-summary"><span><b>{recon.summary.needs_action}</b> perlu tindakan</span><span>{recon.summary.pending} pending</span><span>{recon.summary.reserved} reserved</span><span>{recon.summary.created} created</span></div><div className="dlv-digi-row"><button className="is-secondary" disabled={busy} onClick={()=>void loadRecon()}>Refresh queue</button><button disabled={busy||!gatewayReady||!recon.summary.needs_action} onClick={()=>void runRecon('reconcile_stale',{},'Order stale selesai diperiksa.')}>{busy?'Memeriksa…':'Reconcile stale'}</button></div><div className="dlv-digi-reconcile-list">{recon.orders.slice(0,12).map(o=><article key={o.ref_id}><div><strong>{o.product_name}</strong><code>{o.ref_id}</code><small>{o.product_kind==='postpaid'?'Tagihan':'Prepaid'} · {o.customer_no} · {rupiah.format(Number(o.sell_price||0))}</small><small>Update {date(o.updated_at)}{o.reconciliation_attempts?` · ${o.reconciliation_attempts} reconcile`:''}</small>{o.reconciliation_note&&<em>{o.reconciliation_note}</em>}</div><span data-status={o.status}>{o.status}</span><button disabled={busy||!gatewayReady||!o.needs_action} onClick={()=>void runRecon('reconcile',{ref_id:o.ref_id},`Reconcile ${o.ref_id} selesai.`)}>Periksa</button></article>)}{!recon.orders.length&&<div className="dlv-digi-reconcile-empty">Tidak ada order digital yang tertinggal.</div>}</div><small>Reconciliation tidak melakukan cek status supplier lebih sering dari 1 menit. Order mendekati 90 hari diarahkan ke pemeriksaan manual agar tidak berisiko membuat transaksi baru.</small></section>
 </div></aside>}</div>
}
