import { useEffect, useMemo, useRef, useState } from 'react'
import { gsap } from 'gsap'

type PageId = 'home' | 'market' | 'guide' | 'security' | 'activity' | 'help' | 'legal'
type PageItem = { id: PageId; label: string; eyebrow: string; description: string }
const pages: PageItem[] = [
  { id: 'home', label: 'Beranda', eyebrow: '01', description: 'Ringkasan akun, wallet & layanan' },
  { id: 'market', label: 'Market', eyebrow: '02', description: 'Pulsa, data, PLN, voucher & nomor' },
  { id: 'guide', label: 'Cara kerja', eyebrow: '03', description: 'Wallet, pembelian & status supplier' },
  { id: 'security', label: 'Keamanan', eyebrow: '04', description: 'Proteksi data & status backend' },
  { id: 'activity', label: 'Aktivitas', eyebrow: '05', description: 'Pesanan digital, OTP, deposit & refund' },
  { id: 'help', label: 'Bantuan', eyebrow: '06', description: 'FAQ, reference ID & dukungan' },
  { id: 'legal', label: 'Legal', eyebrow: '07', description: 'Terms, privasi, refund & kebijakan' },
]
function normalizePage(hash = window.location.hash): PageId {const value=hash.replace(/^#\/?/,'').split(/[?&]/)[0].toLowerCase();if(value==='market')return'market';if(value==='guide'||value==='cara-kerja')return'guide';if(value==='security'||value==='keamanan')return'security';if(value==='activity'||value==='aktivitas')return'activity';if(value==='help'||value==='faq'||value==='bantuan')return'help';if(value==='legal'||value==='terms'||value==='privacy'||value==='kebijakan')return'legal';return'home'}
function pageSelector(page: PageId) {if(page==='home')return'.hero';if(page==='market')return new URLSearchParams(window.location.hash.split('?')[1]||'').get('mode')==='nokos'?'.market-flow-page':'.dlv-digital-market';if(page==='guide')return'.dlv51-secondary-page[data-secondary-page="guide"]';if(page==='security')return'.dlv51-secondary-page[data-secondary-page="security"]';if(page==='activity')return'.history-section';if(page==='help')return'.dlv51-secondary-page[data-secondary-page="help"]';return'.dlv51-secondary-page[data-secondary-page="legal"]'}
export default function PageNavigation(){
 const [page,setPage]=useState<PageId>(()=>normalizePage()),[open,setOpen]=useState(false);const dockRef=useRef<HTMLDivElement>(null);const lastPageRef=useRef<PageId|null>(null);const active=useMemo(()=>pages.find(x=>x.id===page)??pages[0],[page])
 const navigate=(next:PageId)=>{setOpen(false);if(next===page&&window.location.hash===`#/${next}`){window.scrollTo({top:0,left:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});return}window.location.hash=`/${next}`}
 useEffect(()=>{const sync=()=>{const next=normalizePage();const previous=lastPageRef.current;const routeChanged=previous===null||previous!==next;lastPageRef.current=next;setPage(next);document.documentElement.dataset.page=next;if(!routeChanged)return;window.scrollTo({top:0,left:0,behavior:'auto'});requestAnimationFrame(()=>{const target=document.querySelector<HTMLElement>(pageSelector(next));if(!target)return;gsap.killTweensOf(target);gsap.fromTo(target,{opacity:0,y:18,scale:.994},{opacity:1,y:0,scale:1,duration:.52,ease:'power3.out',clearProps:'transform'})})};document.documentElement.dataset.page=normalizePage();if(!window.location.hash||window.location.hash==='#top')history.replaceState(null,'',`${window.location.pathname}${window.location.search}#/home`);sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[])
 useEffect(()=>{const capture=(event:MouseEvent)=>{const target=event.target as HTMLElement|null;if(!target)return;const market=target.closest('.hero-actions .button-primary, .cta-card .button-light');if(market){event.preventDefault();event.stopPropagation();navigate('market');return}const brand=target.closest('.site-nav .brand, .footer .brand');if(brand){event.preventDefault();navigate('home')}};document.addEventListener('click',capture,true);return()=>document.removeEventListener('click',capture,true)},[page])
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!dockRef.current?.contains(e.target as Node))setOpen(false)},esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',esc);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',esc)}},[open])
 return <div className={`page-nav-dock${open?' is-open':''}`} ref={dockRef}><button className="page-nav-trigger" type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Pilih halaman"><span className="page-nav-current">{active.label}</span><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m7 9 5 5 5-5"/></svg></button>{open&&<section className="page-nav-menu" aria-label="Navigasi halaman"><div className="page-nav-head"><span>Navigasi</span><small>{active.eyebrow} / 07</small></div><div className="page-nav-list">{pages.map(item=><button key={item.id} type="button" className={page===item.id?'active':''} onClick={()=>navigate(item.id)}><span className="page-nav-index">{item.eyebrow}</span><span className="page-nav-copy"><strong>{item.label}</strong><small>{item.description}</small></span><span className="page-nav-arrow">→</span></button>)}</div></section>}</div>
}
