import { useCallback, useEffect, useState } from 'react'

type Deposit={order_id:string;amount:number;status:string;payment_type?:string|null;midtrans_status_code?:string|null;midtrans_status_message?:string|null;expires_at?:string|null;created_at:string;updated_at:string;credited_at?:string|null}
type Payload={ok?:boolean;wallet_id?:string|null;deposits?:Deposit[]}
type Profile={id?:string;username?:string}
const API='https://ydaeukhqwishlrjyfktk.supabase.co/functions/v1/dlavie-wallet'
const rupiah=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0})
const en=()=>localStorage.getItem('dlavie-language')==='en'
const prof=():Profile|null=>{try{return JSON.parse(localStorage.getItem('dlavie-account-profile-v1')||'null')}catch{return null}}
const date=(v?:string|number|null)=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(en()?'en-US':'id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d)}
const walletRef=(v?:string|null)=>v?`WLT-${v.replaceAll('-','').slice(0,12).toUpperCase()}`:'—'
const method=(v?:string|null)=>({qris:'QRIS',gopay:'GoPay',shopeepay:'ShopeePay',dana:'DANA',ovo:'OVO',bca:'BCA Virtual Account',bni:'BNI Virtual Account',bri:'BRI Virtual Account',permata:'Permata Virtual Account',mandiri:'Mandiri Bill Payment',indomaret:'Indomaret',alfamart:'Alfamart',akulaku:'Akulaku',kredivo:'Kredivo'}[String(v)]||v||'Payment')
const status=(v:string)=>v==='paid'?(en()?'Payment received':'Pembayaran diterima'):v==='pending'||v==='created'?(en()?'Waiting':'Menunggu pembayaran'):v==='expired'?(en()?'Expired':'Kedaluwarsa'):v==='cancelled'?(en()?'Cancelled':'Dibatalkan'):(en()?'Failed':'Pembayaran gagal')
const insideAssistant=(node:Node)=>{const el=node.nodeType===Node.ELEMENT_NODE?node as Element:node.parentElement;return !!el?.closest('.dlv-assistant')}

export default function WalletHistoryEnhancer(){
 const [wallet,setWallet]=useState<string|null>(null),[items,setItems]=useState<Deposit[]>([]),[detail,setDetail]=useState<Deposit|null>(null),[syncAt,setSyncAt]=useState<number|null>(null)
 const sync=useCallback(async()=>{const token=localStorage.getItem('dlavie-wallet-token-v1');if(!token)return;try{const r=await fetch(API,{method:'POST',body:new URLSearchParams({action:'status',wallet_token:token})});const d=await r.json() as Payload;if(r.ok&&d.ok){setWallet(d.wallet_id||null);setItems(d.deposits||[]);setSyncAt(Date.now())}}catch{/* keep current metadata */}},[])
 const enhance=useCallback(()=>{const sheet=document.querySelector<HTMLElement>('.dlv-pay-sheet');if(!sheet)return;const balance=sheet.querySelector('.dlv-balance-bar');if(balance){let x=sheet.querySelector<HTMLElement>('.dlv-wallet-meta');if(!x){x=document.createElement('div');x.className='dlv-wallet-meta';balance.insertAdjacentElement('afterend',x)}const p=prof();x.innerHTML=`<span><small>User ID</small><b>${p?.id||'Guest'}</b></span><span><small>Wallet ID</small><b>${walletRef(wallet)}</b></span><span><small>${en()?'Last sync':'Sinkron'}</small><b>${date(syncAt)}</b></span>`}const list=sheet.querySelector<HTMLElement>('.dlv-history-list');if(!list)return;const paid=items.filter(x=>x.status==='paid').length,pending=items.filter(x=>x.status==='pending'||x.status==='created').length,failed=items.length-paid-pending;let s=sheet.querySelector<HTMLElement>('.dlv-wallet-stats');if(!s){s=document.createElement('div');s.className='dlv-wallet-stats';list.insertAdjacentElement('beforebegin',s)}s.innerHTML=`<span>${en()?'Successful':'Berhasil'} <b>${paid}</b></span><span>${en()?'Waiting':'Menunggu'} <b>${pending}</b></span><span>${en()?'Failed':'Gagal'} <b>${failed}</b></span>`;list.querySelectorAll<HTMLButtonElement>('.dlv-history-row').forEach((row,i)=>{const d=items[i];if(!d)return;row.dataset.dlvDeposit=String(i);let m=row.querySelector<HTMLElement>('.dlv-server-meta');if(!m){m=document.createElement('em');m.className='dlv-server-meta';row.querySelector('span')?.appendChild(m)}m.textContent=`${date(d.created_at)} · ${d.order_id}`})},[items,syncAt,wallet])
 useEffect(()=>{let raf=0,last=0;const run=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{enhance();if(document.querySelector('.dlv-pay-sheet')&&Date.now()-last>5000){last=Date.now();void sync()}})};run();const o=new MutationObserver(mutations=>{if(mutations.length&&mutations.every(m=>insideAssistant(m.target)))return;run()});o.observe(document.body,{childList:true,subtree:true});window.addEventListener('dlavie:state-changed',run);return()=>{o.disconnect();cancelAnimationFrame(raf);window.removeEventListener('dlavie:state-changed',run)}},[enhance,sync])
 useEffect(()=>{enhance()},[enhance])
 useEffect(()=>{const click=(e:MouseEvent)=>{const row=(e.target as HTMLElement)?.closest<HTMLButtonElement>('.dlv-history-row[data-dlv-deposit]');if(!row)return;const d=items[Number(row.dataset.dlvDeposit)];if(!d)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();setDetail(d)};document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true)},[items])
 if(!detail)return null;const p=prof(),mid=detail.midtrans_status_code||detail.midtrans_status_message?`${detail.midtrans_status_code||'—'} · ${detail.midtrans_status_message||'—'}`:'—'
 return <div className="dlv-ledger-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDetail(null)}><section className="dlv-ledger"><button className="dlv-ledger-close" onClick={()=>setDetail(null)}>×</button><header><span>DLAVIE LEDGER · SANDBOX</span><h3>{en()?'Deposit details':'Detail deposit'}</h3><p>{method(detail.payment_type)} · {status(detail.status)}</p><strong>{rupiah.format(detail.amount)}</strong></header><div className="dlv-ledger-grid"><div><small>User ID</small><b>{p?.id||'Guest'}</b></div><div><small>Wallet ID</small><b>{walletRef(wallet)}</b></div><div className="wide"><small>Order ID</small><b>{detail.order_id}</b></div><div><small>{en()?'Method':'Metode'}</small><b>{method(detail.payment_type)}</b></div><div><small>Environment</small><b>Midtrans Sandbox · Core API</b></div><div><small>{en()?'Created':'Dibuat'}</small><b>{date(detail.created_at)}</b></div><div><small>{en()?'Updated':'Diperbarui'}</small><b>{date(detail.updated_at)}</b></div><div><small>{en()?'Paid at':'Dibayar'}</small><b>{date(detail.credited_at)}</b></div><div><small>{en()?'Expires':'Kedaluwarsa'}</small><b>{date(detail.expires_at)}</b></div><div className="wide"><small>{en()?'Midtrans response':'Respons Midtrans'}</small><b>{mid}</b></div></div><footer><span>{status(detail.status)}</span><button onClick={()=>void sync()}>{en()?'Refresh':'Perbarui'}</button></footer></section></div>
}
