import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "npm:@supabase/server";
const ORIGIN="https://drmacze.github.io";
const TOPICS=new Set(["Kemudahan penggunaan","Tampilan & navigasi","Katalog produk","Proses transaksi","Kecepatan website","Bantuan & dukungan"]);
const cors=()=>({"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"});
const safe=(v:unknown,n=700)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,n);
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
async function body(req:Request){const t=(req.headers.get("content-type")||"").toLowerCase();if(t.includes("application/x-www-form-urlencoded"))return Object.fromEntries(new URLSearchParams(await req.text()).entries());return await req.json().catch(()=>({}));}
async function adminAuth(db:any,token:string){if(!token)return null;const q=await db.from("dlavie_assistant_admin_sessions").select("admin_name,expires_at").eq("token_hash",await sha256(token)).maybeSingle();if(q.error)throw q.error;if(!q.data||new Date(q.data.expires_at).getTime()<=Date.now())return null;return q.data;}
Deno.serve(withSupabase({auth:"none"},async(req,ctx)=>{const headers=cors();if(req.method==="OPTIONS")return new Response(null,{status:204,headers});if(req.method!=="POST")return Response.json({error:"method_not_allowed"},{status:405,headers});const origin=req.headers.get("origin")||"";if(origin&&origin!==ORIGIN)return Response.json({error:"origin_not_allowed"},{status:403,headers});try{const b:any=await body(req);const action=safe(b.action,32)||"submit";const db=ctx.supabaseAdmin.schema("api");if(action==="submit"){const userId=safe(b.user_id,80),username=safe(b.username,40)||null,topic=safe(b.topic,80)||null,message=safe(b.message,700)||null,route=safe(b.route,160)||null;const rating=Math.round(Number(b.rating||0));if(userId.length<4)return Response.json({error:"user_required"},{status:400,headers});if(rating<1||rating>5)return Response.json({error:"rating_required"},{status:400,headers});if(topic&&!TOPICS.has(topic))return Response.json({error:"invalid_topic"},{status:400,headers});const recent=await db.from("dlavie_user_feedback").select("id,created_at").eq("user_id",userId).gte("created_at",new Date(Date.now()-10*60*1000).toISOString()).limit(1);if(recent.error)throw recent.error;if((recent.data||[]).length)return Response.json({error:"feedback_too_soon",message:"Feedback baru saja dikirim. Terima kasih."},{status:429,headers});const q=await db.from("dlavie_user_feedback").insert({user_id:userId,username,rating,topic,message,route,source:"main_menu_popup"}).select("id,created_at").single();if(q.error)throw q.error;return Response.json({ok:true,id:q.data.id,created_at:q.data.created_at},{headers});}const admin=await adminAuth(db,safe(b.admin_token,180));if(!admin)return Response.json({error:"admin_auth_required"},{status:401,headers});if(action==="dashboard"){const q=await db.from("dlavie_user_feedback").select("id,user_id,username,rating,topic,message,route,created_at").order("created_at",{ascending:false}).limit(250);if(q.error)throw q.error;const rows=q.data||[];const total=rows.length;const average=total?rows.reduce((a:any,r:any)=>a+Number(r.rating||0),0)/total:0;const ratings=[1,2,3,4,5].map(star=>({star,count:rows.filter((r:any)=>Number(r.rating)===star).length}));const topics=[...TOPICS].map(name=>({name,count:rows.filter((r:any)=>r.topic===name).length,average:(()=>{const x=rows.filter((r:any)=>r.topic===name);return x.length?x.reduce((a:any,r:any)=>a+Number(r.rating||0),0)/x.length:0})()})).sort((a,b)=>b.count-a.count);return Response.json({ok:true,total,average:Number(average.toFixed(2)),ratings,topics,recent:rows.slice(0,60),admin_name:admin.admin_name},{headers});}return Response.json({error:"invalid_action"},{status:400,headers});}catch(e){console.error("dlavie-feedback",e instanceof Error?e.message:e);return Response.json({error:"feedback_server_error"},{status:500,headers});}}));