import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "npm:@supabase/server";

const BASE="https://api.h2h.id/api/trx";
function safe(v:unknown,n=1000){return String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,n)}
async function vault(db:any,name:string){const q=await db.rpc("dlavie_get_vault_secret",{p_name:name});if(q.error)throw q.error;return String(q.data||"")}
async function creds(db:any){const [memberID,pin,password,webhookSecret]=await Promise.all([vault(db,"dlavie_h2h_member_id"),vault(db,"dlavie_h2h_pin"),vault(db,"dlavie_h2h_password"),vault(db,"dlavie_h2h_webhook_key")]);return{memberID,pin,password,webhookSecret}}
async function h2hStatus(c:any,ref:string){const u=new URL(`${BASE}/status`);u.searchParams.set("memberID",c.memberID);u.searchParams.set("pin",c.pin);u.searchParams.set("password",c.password);u.searchParams.set("refID",ref);const r=await fetch(u,{headers:{accept:"application/json"}});const d=await r.json().catch(()=>({}));return{http_ok:r.ok,...d}}
function state(data:any){const s=String(data?.transaction_status||data?.status||"").toLowerCase();if(["success","sukses","completed","berhasil"].includes(s))return"success";if(["failed","gagal","failure","refunded","refund"].includes(s))return"failed";return"pending"}
function hex(bytes:ArrayBuffer){return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("")}
async function expectedHmac(secret:string,message:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return hex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(message)))}
function timingSafeHex(a:string,b:string){const aa=a.trim().toLowerCase(),bb=b.trim().toLowerCase();if(aa.length!==bb.length||aa.length===0)return false;let diff=0;for(let i=0;i<aa.length;i++)diff|=aa.charCodeAt(i)^bb.charCodeAt(i);return diff===0}
function extractRef(payload:any){const candidates=[payload?.refid,payload?.ref_id,payload?.refID,payload?.reference_id,payload?.data?.refid,payload?.data?.ref_id,payload?.data?.refID,payload?.data?.reference_id,payload?.transaction?.refid,payload?.transaction?.ref_id,payload?.transaction?.refID];for(const v of candidates){const x=safe(v,180);if(x)return x}return""}
async function processRef(db:any,c:any,ref:string,message:string,event:string){if(!c.memberID||!c.pin||!c.password)return new Response("integration_not_ready",{status:503});const oq=await db.from("dlavie_digital_orders").select("*").eq("source","h2h").eq("ref_id",ref).maybeSingle();if(oq.error)throw oq.error;if(!oq.data)return new Response("OK",{status:200});const order:any=oq.data,result=await h2hStatus(c,ref);if(!result.http_ok||result.status!==true){await db.from("dlavie_digital_orders").update({reconciliation_note:`Webhook H2H ${event||"event"} diterima tetapi status belum dapat diverifikasi: ${message}`,updated_at:new Date().toISOString()}).eq("id",order.id);return new Response("OK",{status:200})}const data:any=result.data||{},st=state(data),now=new Date().toISOString();const patch:any={supplier_status:safe(data.transaction_status||data.status,60)||null,message:safe(data.status_description||data.reason||result.message||message,800)||null,serial_number:safe(data.serial_number||data.provider_message,900)||null,supplier_price:Number.isFinite(Number(data.price))?Math.round(Number(data.price)):null,buyer_last_saldo:Number.isFinite(Number(data.balance))?Number(data.balance):null,supplier_request_id:safe(data.invoice,160)||order.supplier_request_id,gateway_forwarded:true,raw_response:result,last_checked_at:now,last_reconciled_at:now,reconciliation_note:`Updated from verified H2H webhook${event?` (${event})`:""}`,updated_at:now};if(st==="success"){patch.status="success";patch.completed_at=now}else if(st==="failed"){if(order.status!=="refunded"){const rr=await db.rpc("dlavie_digital_refund_wallet",{p_wallet_id:order.wallet_id,p_ref_id:order.ref_id,p_amount:order.sell_price,p_reason:order.product_kind==="postpaid"?"h2h_webhook_postpaid_failed":"h2h_webhook_prepaid_failed"});if(rr.error&&!String(rr.error.message||"").includes("debit_not_found"))throw rr.error}patch.status="refunded";patch.refunded_at=order.refunded_at||now}else patch.status="pending";const uq=await db.from("dlavie_digital_orders").update(patch).eq("id",order.id);if(uq.error)throw uq.error;return new Response("OK",{status:200})}

Deno.serve(withSupabase({auth:"none"},async(req,ctx)=>{try{const db=ctx.supabaseAdmin.schema("api"),c=await creds(db);
 if(req.method==="POST"){
  const timestamp=safe(req.headers.get("x-webhook-timestamp"),40),signature=safe(req.headers.get("x-webhook-signature"),200),event=safe(req.headers.get("x-webhook-event"),120),raw=await req.text();
  if(!timestamp||!signature)return new Response("missing_signature_headers",{status:401});
  if(!c.webhookSecret)return new Response("webhook_secret_not_configured",{status:503});
  const ts=Number(timestamp),now=Math.floor(Date.now()/1000);if(!Number.isFinite(ts)||Math.abs(now-ts)>300)return new Response("stale_timestamp",{status:401});
  const expected=await expectedHmac(c.webhookSecret,`${timestamp}.${raw}`);if(!timingSafeHex(expected,signature))return new Response("invalid_signature",{status:401});
  const payload=JSON.parse(raw||"{}");const ref=extractRef(payload);if(!ref)return new Response("missing_refid",{status:400});
  return await processRef(db,c,ref,safe(payload?.message||payload?.data?.message||event,1000),event);
 }
 if(req.method==="GET"){
  const u=new URL(req.url),ref=safe(u.searchParams.get("refid")||u.searchParams.get("ref_id"),180),incomingKey=safe(u.searchParams.get("key"),300),message=safe(u.searchParams.get("message"),1000);if(!ref)return new Response("missing_refid",{status:400});if(c.webhookSecret&&incomingKey&&incomingKey!==c.webhookSecret)return new Response("invalid_key",{status:401});return await processRef(db,c,ref,message,"legacy.callback");
 }
 return new Response("method_not_allowed",{status:405});
}catch(e){console.error("dlavie-h2h-callback",e instanceof Error?e.message:"error");return new Response("callback_error",{status:500})}}));
